### ISSUE TITLE
Rich Text Editor doesn't render text from an object

### ISSUE THREAD

**Issue by unixbob** [stsrki/Blazorise#2202] opened 2021-04-14 08:35 UTC
Using the example from here:
https://github.com/stsrki/Blazorise/blob/master/Demos/Blazorise.Demo/Pages/Tests/RichTextEditPage.razor

```cshtml
<RichTextEdit @ref="richTextEditRef"
                              Theme="RichTextEditTheme.Snow"
                              ContentChanged="@OnContentChanged"
                              PlaceHolder="Type your post here..."
                              ReadOnly="@readOnly"
                              SubmitOnEnter="false"
                              EnterPressed="@OnSave"
                              ToolbarPosition="Placement.Bottom">
                    <Editor>
                        <p><b>Hello </b><i>world</i>!</p>
                        <p><br></p>
                        <p>
                            based on: <a href="https://quilljs.com/">Quill</a>
                        </p>
                    </Editor>
```

Renders the HTML within the Editor tabs

If I replace it with an object

```cshtml
<RichTextEdit @ref="richTextEditRef"
                              Theme="RichTextEditTheme.Snow"
                              ContentChanged="@OnContentChanged"
                              PlaceHolder="Type your post here..."
                              ReadOnly="@readOnly"
                              SubmitOnEnter="false"
                              EnterPressed="@OnSave"
                              ToolbarPosition="Placement.Bottom">
                    <Editor>
                        @EssaySections[0].EssaySectionTextLocal
                    </Editor>
```

then it just renders the raw html instead.  tried using @bind-value, @bind-Value and @bind-Text instead but the Editor component doesn't like that

**Comment by stsrki** [comment] 2021-04-14 08:47
@njannink Is this the expected behavior?

**Comment by unixbob** [comment] 2021-04-14 08:56
What I want to do is store the html in a database, then retrieve that html and edit it, and then save it back.  I've attached two screenshots showing how the Blazorise RichTextEdit is rending the database field, vs how the SyncFusion one edits it.

![right](https://user-images.githubusercontent.com/588659/114683150-b14ede80-9d07-11eb-91da-3f0cf61c9ba1.png)
![wrong](https://user-images.githubusercontent.com/588659/114683154-b1e77500-9d07-11eb-889c-55529b8e1d38.png)

**Comment by njannink** [comment] 2021-04-14 13:30
@unixbob which version of Blazorise are you using?

**Comment by unixbob** [comment] 2021-04-14 13:35
0.9.3.4

I did make some progress by replacing the wrapping the text object in a MarkupString in the Editor component.

<Editor> @((MarkupString)@section.EssaySectionTextLocal)</Editor>

I haven't got the two-way binding to work properly yet though. So not sure whether it's my lack of understanding or the component doesn't support what I'm trying to do

**Comment by njannink** [comment] 2021-04-14 19:45
twoway binding isn't going to work simply because of the way how the underlying javascript library works. So you will have to subscribe to the ContentChanged event something like this is done in the examples

```
<RichTextEdit @ref="richTextEditRef2" ContentChanged="OnContentChanged2">
    <Editor>@((MarkupString)contentFromCode)</Editor>
</RichTextEdit>
```

**Comment by unixbob** [comment] 2021-04-14 22:44
I did see that example and hadn't clocked with the ContentChanged event is doing.  thanks for the guidance

**Comment by stsrki** [comment] 2021-04-15 07:28
Can we close this now?

**Closed** 2021-04-15 09:58 UTC
