### ISSUE TITLE
Validation support for AutoComplete component 

### ISSUE THREAD

**Issue by Welchen** [stsrki/Blazorise#1417] opened 2020-10-27 23:11 UTC
The ability to use all of the Validation framework with an AutoComplete control in a form.  

Using it as  a lookup field in a form and the value is required. Would like for it show the same required validation as a TextEdit.

**Comment by stsrki** [comment] 2020-10-28 08:02
I was already thinking of doing this soon. Duplicate of #1350

**Closed by stsrki** 2020-10-28 08:02 UTC
