### ISSUE TITLE
Updating TextEdit Pattern and triggering a revalidation doesn't have any effect.

### ISSUE THREAD

**Issue by cmoissl** [stsrki/Blazorise#1469] opened 2020-11-16 14:31 UTC
**Describe the bug**

Short version:
I have some textEdit fields surrounded by a Validation component. At the root I have a Validations component. After the pattern parameter of the TextEdit component is updated, StateHasChanged() was called and a revalidation is triggered the pattern parameter is still not applied and no validation errors are shown. When I refresh the browser, using F5, the Validation Errors are shown.

Detailed Version:
All textEdit fiels are wrapped by a Component (form here on called editor Component) that I implemented. Now I have one textEdit field in my form that when filled with text triggers after losing the focus another TextEdit field to be required. This is done simply by firing an event that is then received by another editor component  which then sets itself to be required by setting a Property that is passed to the TextEdit component as Pattern parameter to the RegExp of ".+". The Parameter UsePattern of the Validation components are always set to true.

**Expected behavior**
Validation should be done when Pattern field is updated automatically, without requiring to start a validation manually or at least the updated pattern parameter should be considered when starting the validation manually.

**Additional context**
I tried that with  0.9.1 and 0.9.2 of Blazorize.Material.

**Comment by stsrki** [comment] 2020-11-16 14:37
Can you create a small project to reproduce this behavior?

**Comment by cmoissl** [comment] 2020-11-16 15:24
Yes, I did one. I put everything in index.razor.
[ValidationProblem.zip](https://github.com/stsrki/Blazorise/files/5547230/ValidationProblem.zip)

**Comment by cmoissl** [comment] 2020-11-16 15:34
When I add Mode="ValidationMode.Manual" to my example the validation seems to work. Although I expected that without manual validation mode a pattern change is also detected.

Furthermore a change of the mode didnt help in my more complex application.

**Comment by cmoissl** [comment] 2020-11-18 08:35
Have you hade the time to check the project?

**Comment by stsrki** [comment] 2020-11-18 08:43
Sorry not yet. I always take a little break after each major release before I dive into it again :)

It's going on the list for the next patch.

**Comment by stsrki** [comment] 2020-11-19 15:20
I checked your code and I see the problem. You're trying to update pattern dynamically and the problem is that Pattern is only applied once when validation is first created.

I will do my best to fix this and re-apply pattern if change is detected.

**Comment by cmoissl** [comment] 2020-11-19 15:25
Ok great. Thx.

**Comment by stsrki** [comment] 2020-11-19 16:06
I managed to fix it. But the "problem" (if you can call it a problem) is that Blazor works **declaratively**, and you in this case try to work **imperatively**.

So I modified your example slightly to make it work

```cshtml
<Validations @ref="validations" Mode="ValidationMode.Auto">
    <Validation UsePattern="true">
        <TextEdit @bind-Text="@TextA" Pattern="@this.TextAPattern">
            <Feedback>
                <ValidationError>Enter Valid Value</ValidationError>
            </Feedback>
        </TextEdit>
    </Validation>
    <Validation @ref="@validationB" UsePattern="true">
        <TextEdit @bind-Text="@TextB" Pattern="@this.TextBPattern">
            <Feedback>
                <ValidationError>Enter Valid Value</ValidationError>
            </Feedback>
        </TextEdit>
    </Validation>
</Validations>
@code{
    Validations validations;
    Validation validationB;

    string TextAPattern;
    string TextBPattern /*=> !string.IsNullOrEmpty( TextA ) ? ".+" : null*/;

    protected override void OnAfterRender( bool firstRender )
    {
        if ( firstRender )
        {
            validations.ClearAll();
            validations.ValidateAll();
        }
        base.OnAfterRender( firstRender );
    }

    private string textA = string.Empty;
    public string TextA
    {
        get { return textA; }
        set
        {
            this.TextBPattern = ".+";
            this.textA = value;
            StateHasChanged(); // MUST be called before imperatively calling Validate so that Blazor can re-apply parameters
            this.validationB.Validate( TextB );
        }
    }

    public string TextB { get; set; } = string.Empty;
}
```

I will later push changes after I do some more testings. That NuGet patch will be released in the next few days.

**Closed** 2020-11-20 08:36 UTC
Labels: Type: Bug 🐞

**Comment by stsrki** [comment] 2020-11-22 20:40
Patch 0.9.2.1 is just released!
