### ISSUE TITLE
Question: Different kind of validator than data annotations

### ISSUE THREAD

**Issue by njannink** [stsrki/Blazorise#1112] opened 2020-07-08 15:24 UTC
At the moment data annotations are being used to validate field bindings. Is it possible to use a different validator eg one based on FluentValidations?

https://blog.stevensanderson.com/2019/09/04/blazor-fluentvalidation/

**Comment by stsrki** [comment] 2020-07-08 19:46
Duplicate of #995. It's planned for 0.9.3 milestone

**Closed by stsrki** 2020-07-08 19:46 UTC
