### ISSUE TITLE
Wrong color filling of Charts in server-side demo

### ISSUE THREAD

**Issue by macropas** [stsrki/Blazorise#115] opened 2019-06-13 15:10 UTC
Wrong color filling of Charts in server-side demo in comparison with the client-side demo
[Client-side](https://bootstrapdemo.blazorise.com/tests/charts):
![1](https://user-images.githubusercontent.com/7488502/59444182-1254b500-8e06-11e9-91f5-8b1fd1a4f009.png)
[Server-side](https://rcbootstrapdemo.blazorise.com/tests/charts):
![2](https://user-images.githubusercontent.com/7488502/59444243-33b5a100-8e06-11e9-9fa5-c159024eaf15.png)

**Comment by stsrki** [comment] 2019-06-13 15:11
Thanks for report, I will check the problem.

**Comment by jdtcn** [comment] 2019-08-01 06:19
@stsrki, I think I found the problem.

The problem is in this line:
https://github.com/stsrki/Blazorise/blob/38d04753cd458618905c2b41b91f9aba897980ec/Source/Extensions/Blazorise.Charts/ChartData.cs#L362

The "A" variable is a float, so it'll be converted to string using CurrentCulture. In "en-US" culture decimal delimiter is ".", but in some other cultures it is ",".

Thus when current culture decimal delimiter is "," we have
````JS
rgba(100,100,100,0,5)
````
instead of
````JS
rgba(100,100,100,0.5)
````

Possible fix:
````C#
$"{A.ToString(System.Globalization.CultureInfo.InvariantCulture)}"
````

**Comment by stsrki** [comment] 2019-08-01 09:27
@jdtcn You're right, that was the solution. Who knows when would I see that little dot missing :)

It will be in the next 0.8.1

Thanks a lot!

**Closed by stsrki** 2019-08-01 09:27 UTC
Labels: bug, in-progress
