### ISSUE TITLE
No switching to a next element on DateEdit

### ISSUE THREAD

**Issue by dkonstantinov193** [stsrki/Blazorise#1811] opened 2021-02-09 09:24 UTC
**Describe the bug**
On the DateEdit component there are no switching to another element on specific numbers.

**To Reproduce**
1. Go to https://bootstrapdemo.blazorise.com/tests/misc-forms
2. On "DateEdit Sizes" enter some date in any field.
3. Click on the very first element (Day or Month depending on local date format) and enter "01".
4. See that there are no focus switch to month/year element.

**Expected behavior**
Once the element is filled up the component should switch the focus to the next element.

Please note that this occurs only with numbers "01", "02" and "03", on 04 and upper focus switching works fine.

**Comment by stsrki** [comment] 2021-02-09 09:27
What browser do you use? I tried it with Chrome and Firefox and it is working just fine.

**Comment by dkonstantinov193** [comment] 2021-02-09 10:06
Reproduces on both latest Chrome and Firefox (all extensions disabled). On step 3 do you see the other elements being reset and showing "mm.yyyy"? From what I can see, this reproduces when such reset event occurs.

**Comment by stsrki** [comment] 2021-02-09 10:09
![image](https://user-images.githubusercontent.com/900302/107348291-1c412680-6ac7-11eb-9499-907243e7592a.png)

Yes, I type "01" and it goes into the second part as expected. Maybe it has something with current culture for your system or browser?

**Comment by dkonstantinov193** [comment] 2021-02-09 10:42
This was the first thing I've checked, reproduces on brand new AWS VM with en-US cultured Windows and the same browsers. I can see it has some floating nature when different fields are used - when the focus going out to the next field (from Small to Medium) and I click back on small's month (which is already filled up with 01.01.2006) and set it again to 01 sometimes the focus stays on the element but sometimes is switching. I'm refreshing the page to get different behavior.

**Comment by stsrki** [comment] 2021-02-17 13:42
I'm still not able to reproduce this. So closing for now.

**Closed by stsrki** 2021-02-17 13:42 UTC

**Comment by Jossec101** [comment] 2021-04-07 18:39
I can confirm that a similar issue is happening to me @stsrki, when I type 0X it resets my DateEdit and its very frustrating.

My browser is in "en" language (according to navigator.language in JS)

Here's a gif
![2021-04-07_20-37-00](https://user-images.githubusercontent.com/53834183/113917241-42422900-97e1-11eb-960a-8c95d01e3f00.gif)

**Comment by stsrki** [comment] 2021-04-07 19:12
@Jossec101 What Blazorise version you use?

**Comment by Jossec101** [comment] 2021-04-08 10:28
> @Jossec101 What Blazorise version you use?

0.9.3.3 but I have just updated to 0.9.3.4 and it still happens, we did internal tests with input type and it also had issues when binding.

**Comment by thuhaile** [comment] 2021-04-14 19:02
I also have the same issue as @Jossec101

**Comment by Climax85** [comment] 2022-02-14 06:40
Why is this issue closed? I'm facing the same problem @Jossec101 described. When I type a date and enter the month with leding zero the entered day will be reset to 01. Only when entering the month without leading zero everything works as expected.
I'm on the latest Version of blazorise. I can't reproduce the behaviour in the sample on official page. It seems to be related to validation of the DateEdit.

**Comment by stsrki** [comment] 2022-02-14 11:06
The ticket was closed because we couldn't reproduce the issue. We testes with and without the validation.

**Comment by Climax85** [comment] 2022-02-14 14:23
I investigated a little more. I can reproduce the error even on the docs example page. With german localization (Format TT.mm.yyyy) the day is reset when I want to override an existing value.
Example set 14.02.2022. After that try to set another value ex. 15.02.2022. While typing the 02 the day (15) will be erased.

**Comment by stsrki** [comment] 2022-02-14 15:08
It seems it has something to do with different localization settings. For me, it still works on the docs page.

**Comment by Climax85** [comment] 2022-02-14 17:25
I tried with Chrome Version 98.0.4758.82,
Brave [Version 1.35.100 Chromium: 98.0.4758.87](https://brave.com/latest/)
and Edge Version 98.0.1108.50
