### ISSUE TITLE
Datagrid: Filter method by column // Enhancing Filter

### ISSUE THREAD

**Issue by David-Moreira** [stsrki/Blazorise#1978] opened 2021-03-07 18:33 UTC
Hello @stsrki 

I just got a requirement where certain columns that only have a handful of values, like for example:
- **active / inactive**

could have a filter dropdown to select which records to display. 

Taking the example above, If filtering by "**active**", the **Contains** `FilterMethod `isn't very effective as it will also display the "**Inactive**" records due to the contains method.
And can't really change the Filter Method to Equals, as it's a more general setting that affects every column.

What about having the feature on a column by column basis? This could also help with extending so that in the feature you can have a more complex filter feature, where you can also click a button and change the type of the filter being applied on each column.

**This here, is a feature that generally grids have and would be pretty cool:**
![image](https://user-images.githubusercontent.com/22283161/110250409-21cd4780-7f73-11eb-91e1-eb020b9c8b02.png)

And any ideas on how I could implement this feature in the meantime?

**Comment by stsrki** [comment] 2021-03-07 21:18
I think this is a duplicate of #1966. The plan is to implement it for the next preview.

**Comment by David-Moreira** [comment] 2021-03-07 21:41
Not exactly the same, But there are several improvements to be made to filter so yea. 🙂 I might help with this one if you'd like.

As for implementing this with the current Datagrid state any idea?

**Comment by stsrki** [comment] 2021-03-07 21:42
I wanted to dirty my hands on this one. You can review it after I'm done 😉

**Comment by David-Moreira** [comment] 2021-03-07 21:44
Fine. I know that feeling of wanting to develop some feature! 😆 Sure thing.

**Closed** 2021-04-12 19:24 UTC
Labels: Type: Feature ⚙
