### ISSUE TITLE
NumericEdit issues with Min=0

### ISSUE THREAD

**Issue by Mijalski** [stsrki/Blazorise#1696] opened 2021-01-12 11:53 UTC
**Describe the bug**
When NumericEdit has type of float/decimal/double and a step with floating point, it is not correctly calculated on arrow key press.
When the min is set to 0, it is not respected at all.

**To Reproduce**
1. Create \<NumericEdit TValue="decimal" Step="0.1m" Min="0" Decimals="1"/>
2. Input a number and use arrow up to make the number go higher
3. Note that it will follow a pattern similliar to 0 -> 0.1 -> 0.2 -> 0.3 -> 0.4000000000001 -> 0.5000000000002

**Expected behavior**
It should enumerate normally without this wierd bug.
When the Min is set to zero it should not be possible to press a key down to make it go to negative number.

**Comment by stsrki** [comment] 2021-01-12 11:59
Hi, thank you for reporting this but it's a duplicate of #1286 

It's already scheduled for the next milestone so I will close it.

**Comment by Mijalski** [comment] 2021-01-12 12:06
Right, but could you take a look at setting the min=0? It also does not work correctly (it does for eg. 0.1, but then i cannot type in 0.1, because it blocks me if i type in zero).

**Comment by stsrki** [comment] 2021-01-12 12:27
I changed the ticker name and will schedule it for the next milestone along with #1286

**Closed** 2021-04-13 20:09 UTC
Labels: Type: Bug 🐞
