### ISSUE TITLE
Install breaks `@typeparam TableItem` and `@context`

### ISSUE THREAD

**Issue by Gander7** [stsrki/Blazorise#271] opened 2019-09-23 19:09 UTC
Using dotnet version `3.0.100-preview9-014004`

Aftering completing the readme install into a blazor service project.
My pagination breaks which uses `@typeparam TableItem` and `@context`

Sample of my code:
Pagination:
```
@typeparam TableItem
@inherits PaginationBase<TableItem>

...

<table>
    <thead>
        <tr>@GridHeader</tr>
    </thead>
    <tbody>
        @foreach (var item in ItemList)
        {
            <tr>@GridRow(item)</tr>
        }
    </tbody>
</table>
```
Use of Pagination (Page.cs):
```
 <Pagination Items="@data" PageSize="10">
        <GridHeader>
                <th>Field 1</th>
                <th>Field 2</th>
                <th>Field 2</th>
        </GridHeader>
        <GridRow>
                <td>@context.Field1</td>
                <td>@context.Field2</td>
                <td>@context.Field3</td>
        </GridRow>
    </Pagination>
```
Errors Generated:
```
obj\Debug\netcoreapp3.0\Razor\Pages\Page.razor.g.cs(116,162): error CS0246: The type or namespace name 'TableItem' could not be found (are you missing a using directive or an assembly reference?)
Pages\Page.razor(21,25): error CS1503: Argument 1: cannot convert from 'System.Collections.Generic.IEnumerable<MyModel>' to 'System.Collections.Generic.IEnumerable<TableItem>'
Pages\Page.razor(31,22): error CS0103: The name 'context' does not exist in the current context 
Pages\Page.razor(32,22): error CS0103: The name 'context' does not exist in the current context
Pages\Page.razor(33,22): error CS0103: The name 'context' does not exist in the current context
```

Double checked, build was working before install process.
Are there changes I need to make to existing code to get blazorise to play nice?
Am I just missing something?
Or is there something else?

Please let me know if there is any other information that I can provide.

**Comment by stsrki** [comment] 2019-09-23 19:37
I don't recognize any component in your example? Are they all you custom components?

Current version of Blazorise `0.8.5` supports `3.0.0-preview9.19457.4`. Since the newest framework is released just a couple of hours ago I still haven't upgrade it so probably that's the reason for your error.

**Comment by stsrki** [comment] 2019-09-27 13:57
New version is published. Can you confirm the error has gone or still there?

**Comment by stsrki** [comment] 2019-09-30 07:57
Closing as there is no way to reproduce error. If you need more help please reopen the issue.

**Closed by stsrki** 2019-09-30 07:57 UTC
