### ISSUE TITLE
Memory-leak on Server-side Blazor

### ISSUE THREAD

**Issue by FStolte** [stsrki/Blazorise#2165] opened 2021-04-06 14:40 UTC
We have been fighting with strange memory leaks in our Server-side Blazor app for the past weeks, but we could finally pinpoint the cause of the leak, and it lies within the custom ComponentActivator of Blazorise.

*TL;DR: The custom ComponentActivator needs to be scoped instead of singleton, and in long-term the ComponentActivator implementation probably needs to change.*

### Description

The issue is the following: When a transient service is created, normally the DI-container would just create the object, return it and then forget about it. However, when the service is also **disposable**, it needs to keep a reference so that it knows to dispose it when the scope is disposed.
So far, so good. Since the ComponentActivator is currently a singleton, the transient disposable services created by it will be tracked in the root scope of the DI-container, which means they cannot be garbage collected until the root scope is disposed. For Blazor Webassembly this means that all Blazorise UI-Components of one session can only be GCed when its circuit is terminated, which is already a bit inefficient but maybe still acceptable. Unfortunately, for Server-side Blazor this means that all Blazorise UI-Components of all users will remain in memory until the server is restarted. 😟

### How To Reproduce
1. Create a sample Server-side Blazor app with Blazorise
2. Add several Blazorise.Button to a page and reload that page several times
3. Put a breakpoint inside `ComponentActivator.CreateInstance()` and reload to trigger the method
4. Check the field `ServiceProvider._disposables` -> It contains several instances of Blazorise.Bootstrap.Button
5. Wait at least 3 minutes - after this time Blazor terminates a disconnected circuit

#### Expectation
After all circuits are terminated, no references to UI components should be remaining

#### Reality
Checking `ServiceProvider._disposables` again shows that all those references to Blazorise.Buttons are still there

### How to solve
We can mitigate the problem by making the ComponentActivator scoped. Then, Server-side Blazor would behave just as Blazor Webassembly, i.e. UI-components of one session are released once its circuit is terminated.
However, I think that in long-term there should be an improvement to the ComponentActivator, since we still keep all created components around until the end of the session, even if they have already been removed from the UI long ago.

**Comment by stsrki** [comment] 2021-04-06 15:01
Thank you for this very detailed report. I was able to reproduce it on my side and I will fix it for the next patch.

After that, I will see new ways to improve it. The thing is that all components have to be created as transient but as you already said, it can be a problem when they are disposable. Do you have any advice on how to make it better?

**Comment by FStolte** [comment] 2021-04-06 15:14
I thought about that a bit, but so far I couldn't come up with a good solution, unfortunately. One the one hand you need to avoid the automatic disposal from the ServiceProvider, on the other hand you need the automatic disposal that Blazor performs. Both are based on `IDisposable`, and that makes it complicated. Is there maybe a hook somewhere in Blazor that is executed when a component is removed from the UI? That would be the only way I currently see other than not using the ServiceProvider at all...

**Comment by stsrki** [comment] 2021-04-06 15:35
https://chrissainty.com/an-introduction-to-owningcomponentbase/

**Comment by stsrki** [comment] 2021-04-06 16:37
As far as I know, Blazor is the only thing that controls the removal of component instances. The same thing was for creating them. That is why I introduced the IComponentActivator and submitted PR to the .Net Core team, so I can hook into the components creation process. But for destroying them there is not a way so far.

**Comment by FStolte** [comment] 2021-04-07 06:57
Hmm, maybe there's another way. You are only using the ComponentActivator to instantiate the provider-specific components in place of the generic Blazorise ones, right?
That should be possible without using the ServiceProvider. The ComponentActivator can have a Dictionary<Type,Type>, and whenever a Type should be instantiated that has a key in the dictionary, the dictionary value is taken instead. Then, in the `Add...Provider()`-methods, you add all the mappings to that Dictionary instead of to the ServiceProvider. That way, the instantiation can completely be done by the `Activator`, and the Blazor-framework should take care of the rest.

**Comment by stsrki** [comment] 2021-04-07 07:16
It's not so simple. The solution you mentioned was how Blazorise was working before ComponentActivator was introduced. And it was a pain to work with. Back then I didn't have any way to access `Activator.CreateInstance` so I had to do some workarounds for provider-specific components. That was problematic because I had to create a second component instance inside of the component created by Blazor, and then proxy everything to it. It was a mess.

ComponentActivator helped a lot since now all I need is to register provider-specific components within DI and the framework will take care of the rest.

**Comment by stsrki** [comment] 2021-04-07 08:46
What about just making IComponentActivator transient?

`serviceCollection.Replace( ServiceDescriptor.Transient<IComponentActivator, ComponentActivator>() );`

Seems to work just fine.

**Comment by stsrki** [comment] 2021-04-07 09:25
Should be fixed now. Any other change is breaking-change and if needed should be done in 0.9.4 or later. We'll see how it behaves,

**Closed by stsrki** 2021-04-07 09:25 UTC
Labels: Type: Bug 🐞

**Comment by FStolte** [comment] 2021-04-07 11:41
Transient is as good as scoped in this case, but not better, since the ComponentActivator is created together with each circuit (for Server-side) and therefore will live as long as the circuit, even if it is transient.

I am currently testing a solution without the ServiceProvider and will post a PR once its done so you can take a look.
