### ISSUE TITLE
DateEdit only for one time use

### ISSUE THREAD

**Issue by Andy74** [stsrki/Blazorise#388] opened 2019-11-28 12:57 UTC
**Describe the bug**
when there is a DateEdit component, one can only set the value on the UI for one time. Each new attempt to open the dialog for it will just pop up this dialog which disappears automatically at once.

**To Reproduce**
1. this is an example code:
<DateEdit @bind-Date="@DummyDate" />
@code {
        DateTime? DummyDate;
        protected override async Task OnInitializedAsync()
        {
            DummyDate =DateTime.Now;
        }
}
2. when opening this page, click on the DateEditcomponent and select a date.
3. the dialog disappears, which is correct.
4. now click a second time on this DateEditcomponent.
5. the dialog for selecting the date will just pop up for a few milliseconds.

**Expected behavior**
I would expect to be able to set the date muliple times.

**Additional context**
I use 0.8.6.2 and have tested it with chrome.

**Comment by stsrki** [comment] 2019-11-28 13:04
Thanks for the report. The bug is already known and it will be fixed in 0.8.8.

I will close this as I already have a tracking ticket in #239

**Closed by stsrki** 2019-11-28 13:04 UTC

**Comment by SRathodTatva** [comment] 2020-02-17 09:40
I'm facing this issue with V0.8.8.3.

**Comment by stsrki** [comment] 2020-02-17 11:56
@SRathodTatva 
The problem is actually on daemonite side so that's the reason why this is still not done. @djibe is working on new and updated version of Material. You can track the progress and use it once it's done. https://github.com/djibe/material
