### ISSUE TITLE
[Annoying] Rider display error on Button Clicked method

### ISSUE THREAD

**Issue by gaffkins** [stsrki/Blazorise#901] opened 2020-05-16 20:15 UTC
Only on Button Clicked. Example below.
![Zrzut ekranu 2020-05-16 o 22 12 04](https://user-images.githubusercontent.com/10144726/82129376-8e980b00-97c2-11ea-8611-73c0988c644e.png)

**Comment by stsrki** [comment] 2020-05-16 20:21
Can you post a sample of your markup and Submit method?

**Comment by gaffkins** [comment] 2020-05-16 20:25
I think if you change EventCallback to EventCallback<MouseEventArgs> problem will be solved.

My method.
async Task Submit()
{
    validations.ClearAll();
    ....
}

**Comment by stsrki** [comment] 2020-05-16 21:34
I'm not sure this is the Blazorise problem, or Blazor for that matter. `Clicked` as an empty `EventCallback` without arguments should be perfectly fine. There are also another event callbacks that are also without arguments. If the problem is that this one is called Clicked and Rider is expecting an argument than for all I can see it's the problem with Rider.

**Comment by gaffkins** [comment] 2020-05-16 21:37
Yea, I understand. For information the same issue is in Visual Studio Code.

**Comment by njannink** [comment] 2020-05-18 20:11
Rider / Resharper just cannot handle Blazor / Razor code very well. Just ignore it and hope it will be fixed by JetBrains in some upcoming release

**Comment by stsrki** [comment] 2020-05-19 11:09
I'm closing this as it's not really a Blazorise issue.

**Closed by stsrki** 2020-05-19 11:09 UTC
