### ISSUE TITLE
Bootstrap Demo for Server Side is not displayed correctly

### ISSUE THREAD

**Issue by macropas** [stsrki/Blazorise#111] opened 2019-06-10 12:16 UTC
Your [Bootstrap Demo for Server Side](https://rcbootstrapdemo.blazorise.com/) is not displayed correctly. 
![2019-06-10_150817](https://user-images.githubusercontent.com/7488502/59194692-88e97c80-8b92-11e9-9f65-1e7b072be736.png)

**Comment by stsrki** [comment] 2019-06-10 12:22
I have made CD lately for the demo projects and it seems that required js and css files were not copied for the server-side demo project. The issue is now fixed. Thanks for the report.

**Closed by stsrki** 2019-06-10 12:22 UTC
