### ISSUE TITLE
Feature Requst Toast

### ISSUE THREAD

**Issue by janellesnowy** [stsrki/Blazorise#104] opened 2019-06-04 04:34 UTC
Hi, I would like to see a Toast feature like this

https://chrissainty.com/blazor-toast-notifications-using-only-csharp-html-css/

**Comment by stsrki** [comment] 2019-06-04 07:57
I will see what I can do. The component is fairly easy to create but the problem is to make it to work for different css frameworks. For example color names are not the same for bootstrap and for bulma. Maybe this task can be a part of #101 theming. I will need to investigate more but until then maybe you can try a `<Snackbar>` component.

**Comment by janellesnowy** [comment] 2019-06-06 09:05
Thanks, I looked at the Snackbar, it does not allow me to create the text dynamically?

**Comment by stsrki** [comment] 2019-06-06 15:06
Can you give me an example on what you mean by creating the text dynamically?

**Comment by janellesnowy** [comment] 2019-06-08 08:20
Like javascript Alert, I can call it from code without needing to add into the page

**Comment by stsrki** [comment] 2019-06-08 13:34
I think something can be done to create the snackbar dynamically. In the meantime maybe you can create your own _root_ component and cascade it down through the component tree. eg.

**MyRootComponent.razor**
```
<CascadingValue Value=this>
    @ChildContent
</CascadingValue>

<Snackbar ref="snackbar">
    <SnackbarBody>
        @message
    </SnackbarBody>
</Snackbar>
@functions{
    string message;

    public void ShowMessage(string message)
    {
        this.message = message;
        snackbar.Show();
    }
}
```

**SomeChildComponent.razor**
```
void OnSomeAction()
{
    Root.ShowMessage("Hello from child component!");
}

[CascadingParameter] protected MyRootComponent Root { get; set; }
```

**Comment by stsrki** [comment] 2020-04-20 10:01
Closing as Snackbar already have similar functionality.

**Closed by stsrki** 2020-04-20 10:01 UTC
Labels: Status: Investigate, Type: Feature ⚙
