### ISSUE TITLE
System.NullReferenceException after Migrating to .Net 5 and to Blazorise 0.9.2 (from 0.9.1)

### ISSUE THREAD

**Issue by cmoissl** [stsrki/Blazorise#1468] opened 2020-11-16 13:57 UTC
**Describe the bug**

Im calling validations.ValidateAll() in OnAfterRenderAsync in Index.razor to receive the global validation status via the StatusChanged event of the Validations component. 

When I call it I get an NullreferenceException at
>	Blazorise.dll!Blazorise.Validation.OnValidatingAll(Blazorise.ValidatingAllEventArgs e) Line 158	C#

because inputcomponent is null. 

Thats my code in index.razor:

`
     protected override async Task OnAfterRenderAsync(bool firstRender)
       {

        await base.OnAfterRenderAsync(firstRender);
        if (firstRender)
        {
            SetStatus(Blazorise.ValidationStatus.None);

            validations.StatusChanged = EventCallback.Factory.Create<ValidationsStatusChangedEventArgs>(this, o => SetStatus(o.Status));
            validations.ValidateAll();
            if (this.formItem != null)
            {
                await FormGenerator.Helper.JsInterop.PostValidationStatus(iJsRuntime, this.formItem.Status);
            }
        }
    }
`
**Additional context**

Before the migration this has worked without problems.

**Comment by NicolasFVS** [comment] 2020-11-17 16:05
I have the same problem.
My valdator 
        <Validations @ref="mobj_Validations" Mode="ValidationMode.Manual" Model="mvm_ManifestationInfos">
 And when I try to validate the form in may submit button
if (mobj_Validations.ValidateAll())
        {...
raise a NullreferenceException

Is there another way to use it?

**Comment by Messiremi** [comment] 2020-11-17 16:34
Same issue, bypassed with

**Comment by stsrki** [comment] 2020-11-17 16:40
Can you both create a small project to reproduce the error?

**Comment by NicolasFVS** [comment] 2020-11-17 16:46
We found the cause of the problem
An error when we use a tiny editor like a field to validate
An error when we use an unnecessary validation tag encompassing other validation tags
Thank-you for your quick answer

**Comment by stsrki** [comment] 2020-11-17 21:25
@NicolasFVS So, it's working now?

**Comment by cmoissl** [comment] 2020-11-18 16:01
I think the best solution would be to just introduce an null handling for inputcomponent in Source/Blazorise/Validation.razor.cs, that fixed it for me:

        private void OnValidatingAll( ValidatingAllEventArgs e )
        {
          if(inputComponent == null)
              {
               return;
                }
            e.Cancel = Validate( inputComponent.ValidationValue ) == ValidationStatus.Error;
        }

**Comment by stsrki** [comment] 2020-11-18 20:33
A null exception might be the sign of a bigger problem. That's why I would like to have a real-world code sample from so I can see what exactly is wrong. It's easiest to just return if `inputComponent` is null but maybe that will just hide the actual problem.

**Comment by cmoissl** [comment] 2020-11-19 07:40
I did one. To trigger the problem it is sufficient to nest two validation elements.  But as I dont know the entire code their might be other cases triggering the NullReferenceException and handling null references is never wrong. 
[ValidationProblem.zip](https://github.com/stsrki/Blazorise/files/5565134/ValidationProblem.zip)

**Comment by stsrki** [comment] 2020-11-19 09:24
Well, that's your problem. Nesting of `Validation` component is not supported. Or at least it shouldn't be needed. In your example you have two Validation's nested inside of parent Validation. Both of nested validations have a TextEdit so they are OK. But parent validation doesn't have any input field and that's why it's failing.

**Comment by cmoissl** [comment] 2020-11-19 09:38
The application Im developing and in which this Exception is thrown uses blazorise to generates a UI dynamically by a provided XML. The application has no nested Validation. In the sample project I just used that to demonstrate the problem. 

Because of the lack of time I wasn't able up to know to investigate what the real problem is. If handling the variable being null is not a viable solution to you than this is ok. But instead of this I want to suggest another option: Maybe a guard could be introduced that is giving a hint that the Validation is used in a context where it is not allowed. That would prevent than such nullpointer dereference problem which could also happen in other scenarios apparently.

**Comment by stsrki** [comment] 2020-12-01 16:29
Closing since it's not a supported scenario.

**Closed by stsrki** 2020-12-01 16:29 UTC
