### ISSUE TITLE
Export DataGrid data to csv file

### ISSUE THREAD

**Issue by SunnyOswal** [stsrki/Blazorise#1248] opened 2020-08-13 17:27 UTC
**Describe the solution you'd like**
Export DataGrid data to csv file via a button on the grid next to the new command button.

**Comment by stsrki** [comment] 2020-10-04 17:02
Hi, sorry for not answering before. This is a duplicate of #1349. Unfortunately I don't have a plan to do export within Blazorise, so closing this ticket.

**Closed by stsrki** 2020-10-04 17:02 UTC
