### ISSUE TITLE
Modalsize didn't work

### ISSUE THREAD

**Issue by martinscholz83** [stsrki/Blazorise#789] opened 2020-04-22 07:58 UTC
**Describe the bug**
Setting Size of a Modal to `Large` or `ExtraLarge` didn't work. Modal always stays at small size. That worked in older versions. Im using `0.9.0`

**Comment by stsrki** [comment] 2020-04-22 08:15
Duplicate of #788

**Closed by stsrki** 2020-04-22 08:15 UTC
