### ISSUE TITLE
DataGrid doesn't work properly when passing IEnumerable type to "data" attribute

### ISSUE THREAD

**Issue by satwo** [stsrki/Blazorise#389] opened 2019-11-28 15:20 UTC
When passing an IEnumberable type to the "data" attribute of DataGrid, the DataGrid mostly renders and populates correctly, but several event handlers (ex. RowInserted, RowUpdated, RowRemoved) do not fire. The "New" button doesn't render properly either. 

Casting the IEnumerable<t> to a List<t> solves the issue.  This was tricky to track down because the docs specify IEnumerable (https://blazorise.com/docs/extensions/datagrid/) but the example demo uses a List type (https://github.com/stsrki/Blazorise/blob/master/Tests/Blazorise.Demo/Pages/Tests/DataGridPage.razor). 

Not sure whether this is better characterized as an actual bug or a documentation issue.

**Comment by stsrki** [comment] 2019-11-28 15:34
Hi @satwo 

`IEnumerable` is used for `Data` because that's the basic type that can support enumerating, filtering with linq, sorting etc. If I would make it a `IList` or `ICollection` then I would limit a use case for the users of my library.

The reason why event handlers are not firing is probably because your list is JUST `IEnumerable`. And `IEnumerable` cannot be changed. That's why I'm checking internally if the `Data` is also of type `ICollection` so I can add, remove or change the items.

**Comment by satwo** [comment] 2019-11-28 15:56
Hi @stsrki ,

Thanks for the explanation - that makes sense. Perhaps it would be worth doing a compile-time check of the `Data` type and throwing an error if it's not `ICollection`? I'd be happy to take a stab at it.

**Comment by stsrki** [comment] 2019-11-28 16:02
I never consider it and I'm not sure compile-time check is possible. If it's possible I think it would be an overkill.

Maybe the better way is to throw an Exception if `Data` is not `ICollection`. Or just log warning message into console.

**Comment by richbryant** [comment] 2019-11-28 21:49
Try using `ObservableCollection` - that was designed for databinding.  If you want to get multithreaded about ti and you're familiar with the System.Reactive assembly, you might also want to try Roland Pheasant's amazing [DynamicData](https://github.com/reactiveui/DynamicData) although that can do a whole lot more than just bind to a grid.

**Comment by stsrki** [comment] 2020-04-20 10:31
This should be fixed in the latest v0.9. Please reopen if problem still persist.

**Closed by stsrki** 2020-04-20 10:31 UTC
