### ISSUE TITLE
Blazor server - issue in component cleanup

### ISSUE THREAD

**Issue by Unlink** [stsrki/Blazorise#1920] opened 2021-02-25 19:00 UTC
**Describe the bug**
I tried to fix RichTextEdit disposal in https://github.com/stsrki/Blazorise/pull/1867
but I think that issue is bigger.

When we have a page with components that have some JS cleanup For example buttons. When the component is disposed, js function is called.
![obrázok](https://user-images.githubusercontent.com/9026197/109200020-5fc2b280-77a0-11eb-9b98-59744ff6a742.png)
This is ok in the case of for example navigation to another page. But if the user closes the tab, JSRuntime is not available anymore. This will cause task to be paused (or something else?). After some time all of those tasks are canceled (as we can see in case of RichTextEdit). This will cause slow down of blazor app (probably due to exception handling).

**To Reproduce**
1. Make a page with lots of buttons (500)
2. Refresh the page a few time
3. The app became very slow

I'm not sure how to fix it, maybe using IComponentContext.IsConnected?
https://github.com/dotnet/aspnetcore/issues/9613

**Comment by stsrki** [comment] 2021-02-25 20:04
I think you're right. This `async void` was an overlook on our side. From what I can see there is no reason why it cannot be made `ValueTask`.

@njannink What do you think? See the last comment for reference #1867

**Comment by stsrki** [comment] 2021-02-25 20:32
Guys, check #1921

**Comment by njannink** [comment] 2021-02-25 23:14
Looks good to me

**Comment by Unlink** [comment] 2021-02-26 07:19
Thanks, this is the solution for exceptions showing in the error log for RTE.
But I think that there is still an issue with all components being disposed after the connection closes.

In addition to my example
try to set JSInteropDefaultCallTimeout to for example 5 seconds (instead of 1 minute by default).
This will show slow down after 5 seconds of the first page reload.
```
services.AddServerSideBlazor().AddCircuitOptions(o =>
{
     o.JSInteropDefaultCallTimeout = TimeSpan.FromSeconds(5);
});
```

In VS I can confirm those exceptions
![obrázok](https://user-images.githubusercontent.com/9026197/109267688-40f90600-780a-11eb-96da-31377e531417.png)

They are not shown in the error log, which's good, but I think that they are slowing down the overall performance of the server.
If I increase Timeout, the slow down occurs later because those tasks are being canceled later.

**Comment by stsrki** [comment] 2021-02-26 08:54
@Unlink How do I reproduce the errors? I've added `o.JSInteropDefaultCallTimeout = TimeSpan.FromSeconds(5);` but still nothing shows.

**Comment by stsrki** [comment] 2021-02-26 10:14
Hi @David-Moreira, I would also like to have your input on this issue. If it takes a problem on server-side Blazor we should come to a solution before 0.9.3 is released.

**Comment by Unlink** [comment] 2021-02-26 12:30
I created simple repo with blazorise and 100 buttons in the index.
https://github.com/Unlink/Blazorise-100ButtonsExample

I created a screenshot from VS.
Those are not regular errors shown in the output
![obrázok](https://user-images.githubusercontent.com/9026197/109298038-43bc2100-7833-11eb-8f25-1f6b3b766fe3.png)

But I also tried this simple application and I cant see a slowdown in it. Maybe there is something else happening in my app.
I will investigate but it happens only on page with lots of blazorise components. Those exceptions maybe slowdowns the app but not very significantly and issue may be in a different place...

**Comment by stsrki** [comment] 2021-02-26 12:41
You're working on 0.9.2.5 while mine is 0.9.3-preview. I think those issues might be fixed in new versions

**Comment by Unlink** [comment] 2021-02-26 13:43
For me, with latest 77cb094080c03b546dc37d475a2e65f5cea6281c is same.

**Comment by stsrki** [comment] 2021-02-26 13:47
Hmm, something must be different in your project.

**Comment by David-Moreira** [comment] 2021-02-26 13:50
Not able to reproduce with latest dev093. Can you update your repo with the latest version so we can test.

If I'm not wrong:
These two commits should have fixed that by clearing running stuff on the afterRender if it's disposed..
Commit 959a7d10	+ Commit **cb6538eb**

Also I'm not sure Commit **cb6538eb** is already on the latest release.

Unless we're speaking about a very specific race condition...

**Comment by stsrki** [comment] 2021-02-26 13:53
Commit 959a7d10 is already released, but cb6538e is still not. I can make a new release if needed.

**Comment by David-Moreira** [comment] 2021-02-26 13:56
That must be it, then. I think it's important to have  cb6538e on the latest RC then. And then ask @Unlink  to retest with the new rc. 
If it still happens we do have to take a thorough look at it, I'll help.

Also if this is happening on live 0.9.2, and these commits fix it, I'm guessing we could patch it, @stsrki ?

**Comment by stsrki** [comment] 2021-02-26 13:58
Yep, I will make it now, along with #1921

**Comment by stsrki** [comment] 2021-02-26 14:02
A new preview is released on MyGet now.

**Comment by Unlink** [comment] 2021-02-26 19:03
I tested it more and it seems that it doesn't cause a slowdown on the production server.
It could be in some weird Visual Studio settings, that my VS shows internal app exceptions. During debugging I still have those messages when I pressing F5 on my page. But it happens only during debugging. So I think that it is OK and it is a way, how it should works in blazor.


I checked #1921 again and I realized that is not good now.

Before my fix, it was actually working, because it calls async void method asynchronously and dotNetRef was disposed regardless of DestroyEditor(richTextEdit.EditorRef); works or not.

Now you put await there so if this fails, the whole method fails and dotNetRef.Dispose(); will not be called.
 https://github.com/stsrki/Blazorise/blob/77cb094080c03b546dc37d475a2e65f5cea6281c/Source/Extensions/Blazorise.RichTextEdit/RichTextEditJsInterop.cs#L66

You should put try catch or something else there.

You can test it:

Put breakpoint on 
dotNetRef.Dispose();

navigate to the page with RTE.
navigate to different page -> dotNetRef.Dispose(); is called.
now go back to the page with RTE
close browser tab -> await DestroyEditor( richTextEdit.EditorRef ); is called, after timeout (1minute by default) this method fails and dotNetRef.Dispose(); is not called.

**Comment by David-Moreira** [comment] 2021-02-27 01:05
hmm the buttons js interop throwing a System.Threading.Tasks.TaskCanceledException wasn't that easy to reproduce and seems like an out of the ordinary situation, I had to like bump the number of components even higher and set quite a low js timeout...

Seems just like a race condition and nothing that we could do about it. The task is initiated and theres a CancellationToken based on the timeout provided... The task isn't completed on time, so it throws a TaskCancelledException.

Here's the source code for JSRuntime https://github.com/dotnet/aspnetcore/blob/main/src/JSInterop/Microsoft.JSInterop/src/JSRuntime.cs
and this thread on the asp.net core repo seems to be exactly about that:
https://github.com/dotnet/aspnetcore/issues/18875 

I would say this is not a realistic case, and shouldn't be happening on real world scenarios.

**Comment by David-Moreira** [comment] 2021-02-27 01:10
Oh, and there's this open issue to make it clearer, why the task was cancelled:
https://github.com/dotnet/aspnetcore/issues/21384

**Comment by Unlink** [comment] 2021-02-27 13:52
That makes sense, blazor automatically catches all TaskCancelledExceptions so you don't see them. @David-Moreira how do you test it? Did you close the browser or refresh the page by F5? Because in this case, I think that blazor detect connection close, so it destroys circuit, witch involves Dispose call on all components. This Dispose call in case of Button tries to call js function, which obviously can't do, so this call is canceled after the timeout.

It really happens, but according to my latest tests, it is an issue only on debug because Visual studio tries to log all of those exceptions, which is slow. In the deployed application, I cannot see any performance issues regardless of this. It could be nice to handle this situation somehow, but my performance problems weren't caused by this.

**Comment by stsrki** [comment] 2021-03-01 07:35
Given this is more the Blazor issues, can we close this now?

**Comment by Unlink** [comment] 2021-03-01 08:37
Yes, but pls, check my comment for RTE https://github.com/stsrki/Blazorise/issues/1920#issuecomment-786836445

**Comment by stsrki** [comment] 2021-03-01 09:15
#1939 now handles the RTE exception. I made a _fix_ according to the links provided by the @David-Moreira. There are no better options for now.

But the problem can still be seen. Probably by some other Blazorise component. It's hard to know which one until I test them all.

**Comment by stsrki** [comment] 2021-03-01 13:46
I'm trying to come up with a clean solution for this but I don't think there is an easy way. So far I tried making everything use IAsyncDisposable with #1941 but it seems the "problem" is still present.

@David-Moreira @Unlink @njannink I would be grateful if you could also look at #1941 and add some feedback. Even if it doesn't fix this issue, maybe it's good to be merged for the future.

**Comment by njannink** [comment] 2021-03-01 14:19
Reviewed and added some comments

**Comment by stsrki** [comment] 2021-03-01 14:20
> Reviewed and added some comments

Thank you @njannink

**Comment by stsrki** [comment] 2021-03-03 13:54
https://github.com/stsrki/Blazorise/pull/1941#issuecomment-789619374

**Closed** 2021-03-07 14:22 UTC
Labels: Type: Bug 🐞
