### ISSUE TITLE
OnFieldChanged not fired when some field is changed

### ISSUE THREAD

**Issue by vladop** [stsrki/Blazorise#1839] opened 2021-02-13 20:43 UTC
On `EditContext` of `EditForm `there is event `FieldChanged`.
I would like to use this event to detect if any of the field has been changed(if form is "dirty")
But it seems that event is not fired.
If I manually call OnNotify... inside onchanged then it works but ofcourse I don't want to do it manually for every field.
```
 var fieldIdentifier = new FieldIdentifier(Mymodel, nameof(Mymodel.MyProperty));
                                         EC.NotifyFieldChanged(fieldIdentifier);
```

**Comment by stsrki** [comment] 2021-02-15 08:18
This is a duplicate of #996 

It was fixed as part of #1750

**Closed by stsrki** 2021-02-15 08:18 UTC
