### ISSUE TITLE
DataGrid does not refresh data when page size is changed

### ISSUE THREAD

**Issue by gkapelevich** [stsrki/Blazorise#1563] opened 2020-12-02 14:22 UTC
DataGrid does not refresh data when page size is changed in large data scenario with ReadData event handler.

1. Create DataGrid with ReadData method:
````
	<DataGrid TItem="Employee"
			Data="@employeeList"
			ReadData="@OnReadData"
			TotalItems="@totalEmployees"
			ShowPager="true"
			ShowPageSizes="true">
	…
	</DataGrid>
````
2. Change page size to 25 items per page.
3. Nothing happens.

I would expect ReadData event handler to be called to load new page of data from the server.  Another option is to provide PageSizeChanged event (similar to PageChanged) so caller/parent can refresh the data programmatically.

**Comment by stsrki** [comment] 2020-12-02 14:26
Duplicate of #1558

**Closed by stsrki** 2020-12-02 14:26 UTC
