### ISSUE TITLE
DropdownList issue with ChangeHandler

### ISSUE THREAD

**Issue by sjthompsonengl** [stsrki/Blazorise#974] opened 2020-06-11 14:28 UTC
Trying to use your sample as per: https://blazorise.com/docs/extensions/dropdownlist/

The ChangeHandler object has a value of 4120208 which doesn't correspond to my list of 4 values!

The list displays as expected, but selecting a value throws a memory violation error

**Comment by stsrki** [comment] 2020-06-11 16:44
Can you show me your code?

**Comment by sjthompsonengl** [comment] 2020-06-11 16:53
I copied your example as per the above page, I've tried a SelectList instead and that seems to work fine

**Comment by stsrki** [comment] 2020-06-12 12:41
Just copied the code from the example and it works just fine. I will need to see your list of values, maybe there is a problem?

**Comment by stsrki** [comment] 2020-12-01 14:56
Closing since I cannot reproduce the error.

**Closed by stsrki** 2020-12-01 14:56 UTC
