### ISSUE TITLE
RadioGroup binding has not worked correctly since 0.9.2-preview3

### ISSUE THREAD

**Issue by dfkeenan** [stsrki/Blazorise#1300] opened 2020-09-07 05:22 UTC
**Describe the bug**
`RadioGroup` does not update bound property. More precisely, it updates it and immediately set's it back to the previous value. I worked this out by logging changes in the view models property changed event. I went back through previews 7-3. Stopped working in preview 4.

**To Reproduce**
1. Add `RadioGroup` to page. (WASM project)
2. Run website.
3. Click on `Radio`

**Expected behavior**
Update bound property to the selected value.

This works:
```html
<RadioGroup TValue="bool" Inline="true" Name="TheRadio" @bind-CheckedValue="@vm.Property">
    <ChildContent>
        <Radio TValue="bool" Value="@(true)">Yes</Radio>
        <Radio TValue="bool" Value="@(false)">No</Radio>
    </ChildContent>
</RadioGroup>
```

This does not:
```html
<Field ColumnSize="ColumnSize.Is6">
    <FieldLabel>The label</FieldLabel>
    <FieldBody>
        <RadioGroup TValue="bool" Inline="true"  Name="TheRadio"  @bind-CheckedValue="@vm.Property">
            <ChildContent>
                <Radio TValue="bool" Value="@(true)">Yes</Radio>
                <Radio TValue="bool" Value="@(false)">No</Radio>
            </ChildContent>
        </RadioGroup>
    </FieldBody>
</Field>
```

Neither does this:
```html
<Validations @ref="validations" Mode="ValidationMode.Auto" Model="@vm" ValidateOnLoad="false">
    <Validation>
        <RadioGroup TValue="bool" Inline="true" Name="TheRadio" @bind-CheckedValue="@vm.Property">
            <ChildContent>
                <Radio TValue="bool" Value="@(true)">Yes</Radio>
                <Radio TValue="bool" Value="@(false)">No</Radio>
            </ChildContent>
        </RadioGroup>
    </Validation>
</Validations>
```

**Screenshots**

**Additional context**

**Comment by stsrki** [comment] 2020-09-07 07:58
I can confirm the bug. For now it''s going on backlog for 0.9.3 since current release is already behind schedule. If something changes I will let you know. Thanks for reporting it!

**Comment by dfkeenan** [comment] 2020-09-07 22:59
That's going to be challenging for me. If I managed to fix it what is the chance of the PR being merged? Should I branch from the `dev092` branch if I attempt it?

**Comment by stsrki** [comment] 2020-09-08 06:17
Yes if you manage to fix it, it will be merged. Branch from dev092 is preferred way :)

**Comment by dfkeenan** [comment] 2020-09-08 07:27
This seems like a too simple of a fix...

In `RadioGroup` if I change:

```C#
public override async Task SetParametersAsync( ParameterView parameters )
{
    if ( parameters.TryGetValue<TValue>( nameof( CheckedValue ), out var result ) )
    {
        await CurrentValueHandler( result?.ToString() );
    }
    await base.SetParametersAsync( parameters );
}
```
To this, it works:
```C#
public override async Task SetParametersAsync( ParameterView parameters )
{
    await base.SetParametersAsync( parameters );
    if ( parameters.TryGetValue<TValue>( nameof( CheckedValue ), out var result ) )
    {
        await CurrentValueHandler( result?.ToString() );
    }
}
```

**Comment by dfkeenan** [comment] 2020-09-08 07:43
Should I submit a PR that does just this?

**Comment by dfkeenan** [comment] 2020-09-08 09:35
I created a PR. But it might break it in a different way. If you change the bound property from somewhere else it doesn't update the `RadioGroup`. Guess I jumped the gun.

**Closed** 2020-12-01 16:20 UTC
Labels: Type: Bug 🐞

**Comment by angelru** [comment] 2021-03-15 13:23
I don't know if it's a bug, but when I use this:
```
                            <Validation Validator = "@ ValidationRule.IsNotEmpty">
                                <Field Class = "radioButtonCenter" ColumnSize = "ColumnSize.IsFull.OnTablet.Is6.OnDesktop">
                                    <RadioGroup TValue = "string" Name = "genders" Margin = "Margin.Is4.FromTop" @ bind-CheckedValue = "@ personaRequest.Sexo">
                                        <ChildContent>
                                            <Radio TValue = "string" Value = "@ (" Man ")"> @ localizer ["Man"] </Radio>
                                            <Radio TValue = "string" Value = "@ (" Woman ")"> @ localizer ["Woman"] </Radio>
                                        </ChildContent>
                                        <Feedback>
                                            <ValidationError> @personRequestValidation ["Gender"] </ValidationError>
                                        </Feedback>
                                    </RadioGroup>
                                </Field>
                            </Validation>

```
the validation does it fine, but then when I select one of the radio button it doesn't change the color if I don't hit the other one.

**Comment by stsrki** [comment] 2021-03-15 14:44
@angelru What version you use?

**Comment by angelru** [comment] 2021-03-15 14:58
> @angelru What version you use?

0.9.3

**Comment by stsrki** [comment] 2021-03-15 15:12
It works for me

1. When I open page
![image](https://user-images.githubusercontent.com/900302/111175992-3cbe3e00-85a9-11eb-9bc6-6a749d68fdc2.png)

2. When I click on one option
![image](https://user-images.githubusercontent.com/900302/111176046-46e03c80-85a9-11eb-989a-a637887041e8.png)

**Comment by angelru** [comment] 2021-03-15 15:55
ups i put the code as above, what will i do wrong?

**Comment by stsrki** [comment] 2021-03-15 20:03
@angelru OK with manual mode enabled I was able to reproduce it. Please open a new ticket and I will look into it.

PS. For future reference, please write as many details as possible as that way we can detect the problem much easier. Thanks.
