### ISSUE TITLE
issue with overriding NewCommand button in Grid

### ISSUE THREAD

**Issue by dharriso2020** [stsrki/Blazorise#949] opened 2020-06-01 19:34 UTC
I apologize if this isn't a bug, but I am new to Github so if there is a better place to post this type of thing, please let me know. Bottom line is I am having trouble working with the new button in the grid control. When I click the button, I have a Date Entered column where I would like to default it's value to today's date. I have been unable to find documentation that shows how to "extend" the functionality of that button and write my own code to default the values of the "new" row that is temporarily added when I click the new button.
Another approach I looked at is using EditTemplate. I figure if the value is that default value of 1/1/0001 12:00:00 AM, I could just default it to DateTime.Now.ToString. 

Documentation says we can get or set cell data use CellEditContext, but the below has no effect. I don't get an error either. Its like code isn't there. I still get the default date of 1/1/0001.

                    <DataGridColumn TItem="ProjectLogViewModel" Field="@nameof(ProjectLogViewModel.DateEntered)" Caption="Date" Width="200">
                        <EditTemplate>
                            @{
                                //var DateEntered = ((string)(((CellEditContext)context).CellValue));
                                //DateEntered = DateTime.Now.ToString();

                                ((CellEditContext)context).CellValue = DateTime.Now.ToString();

                            }
                            <TextEdit Text="@((string)(((CellEditContext)context).CellValue))"></TextEdit>
                        </EditTemplate>
                    </DataGridColumn>

Thanks,
D-J

**Comment by stsrki** [comment] 2020-06-02 13:47
It seems this is a duplicate of #934 

The plan is to add this feature in next milestone.

**Closed** 2020-07-05 09:39 UTC
Labels: Area: DataGrid, Type: Feature Request ⛱
