### ISSUE TITLE
Size attribute is not functional for Addons

### ISSUE THREAD

**Issue by a-urel** [stsrki/Blazorise#1646] opened 2020-12-27 09:46 UTC
Size attribute doesn't seem to work when used to resize addon labels.

```
@* Qty *@
<Field>
    <FieldLabel>@L["InvoiceLineQuantity"]</FieldLabel>
    <Addons>
        <Addon AddonType="AddonType.Body">
            <NumericEdit Decimals="0" Size="Size.Small"
                @bind-Value="EditState.Value.SelectedInvoiceLine.Quantity"/>
        </Addon>
        <Addon AddonType="AddonType.End">
            <AddonLabel Size="Size.Small">
                @L[$"UOM:{EditState.Value.SelectedInvoiceLine.Uom}"]
            </AddonLabel>
        </Addon>
    </Addons>
</Field>
```

![image](https://user-images.githubusercontent.com/66084385/103168023-08a46e00-4841-11eb-9c7f-28d59942f547.png)

**Comment by stsrki** [comment] 2020-12-27 12:58
Hi @a-urel, this is a duplicate of #1474. Probably going to work on it for the next milestone.

**Closed by stsrki** 2020-12-27 12:58 UTC
