### ISSUE TITLE
Remove Validation

### ISSUE THREAD

**Issue by martinscholz83** [stsrki/Blazorise#1062] opened 2020-07-01 11:42 UTC
**Is your feature request related to a problem? Please describe.**
For example you have a list of fields in your model which have a `Validator`. When you remove this field from your model the Validator is still there and on `ValidateAll()` this validation will fail.

**Describe the solution you'd like**
`validations` property is private so you can not remove it. Would be nice to have a method to remove a validation. Maybe with some overload to filter by id at which the validator was plugged.

**Comment by stsrki** [comment] 2020-07-01 21:41
Not sure if I understand the problem. Do you have some code to reproduce it?

**Comment by martinscholz83** [comment] 2020-07-02 06:34
For example you have a list where you can dynamically add and remove items. When deleting an item which had an invalid validation, the validation still exists and later the validation will fail.
```html
 @foreach (var item in setting.Values)
                                        {
                                            <div class="form-row">
                                                <div class="form-group col-md-4">
                                                    <label for="input_value">Value</label>
                                                    @if (setting.Type == Types.DWORD)
                                                    {
                                                        item.StringValue = null;
                                                        <Validation Validator="@ValidateDwordValue">
                                                            <TextEdit id="input_value" class="form-control" @bind-Text="item.IntValue">
                                                                <Feedback>
                                                                    <ValidationError>Not a valid number</ValidationError>
                                                                </Feedback>
                                                            </TextEdit>
                                                        </Validation>
                                                    }
                                                    else
                                                    {
                                                        item.IntValue = null;
                                                        <Validation Validator="@ValidationRule.IsNotEmpty">
                                                            <TextEdit class="form-control" id="input_value" @bind-value="item.StringValue">
                                                                <Feedback>
                                                                    <ValidationError>Value required is required</ValidationError>
                                                                </Feedback>
                                                            </TextEdit>
                                                        </Validation>
                                                    }
                                                </div>                                                
                                            </div>
                                            <button class="btn btn-primary" id="btn_delete" type="button" @onclick="(() => DeleteValue(item))">Delete</button>
}
...
...
private void DeleteValue(Value item)
{
    setting.Values.Remove(item);
}
```

**Comment by stsrki** [comment] 2020-07-02 07:59
I understand the problem now. It's because `Validations` component is keeping references to the it's child `Validation` components. I don't predicted this scenario. Thank you for reporting it!

**Comment by dfkeenan** [comment] 2020-08-25 07:38
I have created a whole bunch of tables like this. And just found the issue myself. D:

**Comment by dfkeenan** [comment] 2020-08-25 07:45
The `Validation.Dispose` method should also remove itself from the `ParentValidations`. I hope this is fixed soon or I might have to fork and fix it locally.

**Comment by stsrki** [comment] 2020-08-25 07:50
Actually it's already fixed with #1269 :)

**Closed by stsrki** 2020-08-25 07:50 UTC
