### ISSUE TITLE
Text cursor can't keep up when typing fast in TextEdit field

### ISSUE THREAD

**Issue by ParaScripting** [stsrki/Blazorise#1102] opened 2020-07-07 12:21 UTC
When you type fast in a TextEdit field the text cursor can't keep up and ends up between the text instead of at the end.

The picture below shows what happened when I tried to type 'this is a test while typing fast'. As you can see did the 'i' from 'this' end up at the end of the sentence because of the text cursor bug.
![image](https://user-images.githubusercontent.com/4492615/86780024-8c348d80-c05c-11ea-961a-d513808ae0f5.png)

This happens to me when using the default filter method of Data Grids but also when using the default TextEdit fields 
`<Field Horizontal="true">
    <FieldLabel ColumnSize="ColumnSize.Is2">Name</FieldLabel>
    <FieldBody ColumnSize="ColumnSize.Is10">
        <TextEdit Placeholder="Some text value..." />
    </FieldBody>
</Field>`

**Comment by stsrki** [comment] 2020-07-07 12:23
Duplicate of #1053, I'm working on it. The problem is not that trivial to solve unfortunately.

**Closed by stsrki** 2020-07-07 12:23 UTC
