### ISSUE TITLE
Bulma DataGrid sorting failing

### ISSUE THREAD

**Issue by mattdurham** [stsrki/Blazorise#1347] opened 2020-09-27 23:03 UTC
When sorting in Bulma after the second sorting it fails with `TypeError: i.parentNode is null`. This also appears to be the case with the Bulma Datagrid Demo.

**Comment by stsrki** [comment] 2021-04-15 14:20
I just checked this again and it seems the issue is fixed. Probably it was solved with some other features we recently did on DataGrid. Closing now.

**Closed by stsrki** 2021-04-15 14:20 UTC
Labels: Type: Bug 🐞
