### ISSUE TITLE
RichTextEdit two way binding

### ISSUE THREAD

**Issue by mortezabarzkar** [stsrki/Blazorise#2042] opened 2021-03-16 11:07 UTC
Hi
it is possible to add two way binding  ? or send context object in ContentChanged to handle inside it ?

**Comment by mortezabarzkar** [comment] 2021-03-16 11:53
can you check it pls ?


Error
``
blazor.server.js:21 [2021-03-16T11:50:35.341Z] Error: There was an error applying batch 31.
e.log @ blazor.server.js:21
(anonymous) @ blazor.server.js:21
(anonymous) @ blazor.server.js:21
(anonymous) @ blazor.server.js:21
(anonymous) @ blazor.server.js:21
r @ blazor.server.js:21
e.processBatch @ blazor.server.js:21
(anonymous) @ blazor.server.js:10
(anonymous) @ blazor.server.js:1
e.invokeClientMethod @ blazor.server.js:1
e.processIncomingData @ blazor.server.js:1
connection.onreceive @ blazor.server.js:1
i.onmessage @ blazor.server.js:1
blazor.server.js:8 Uncaught (in promise) TypeError: Cannot read property 'removeChild' of null
    at e (blazor.server.js:8)
    at Object.e [as removeLogicalChild] (blazor.server.js:8)
    at e.applyEdits (blazor.server.js:8)
    at e.updateComponent (blazor.server.js:8)
    at Object.t.renderBatch (blazor.server.js:8)
    at e.<anonymous> (blazor.server.js:21)
    at blazor.server.js:21
    at Object.next (blazor.server.js:21)
    at blazor.server.js:21
    at new Promise (<anonymous>)
e @ blazor.server.js:8
e @ blazor.server.js:8
e.applyEdits @ blazor.server.js:8
e.updateComponent @ blazor.server.js:8
t.renderBatch @ blazor.server.js:8
(anonymous) @ blazor.server.js:21
(anonymous) @ blazor.server.js:21
(anonymous) @ blazor.server.js:21
(anonymous) @ blazor.server.js:21
r @ blazor.server.js:21
e.processBatch @ blazor.server.js:21
(anonymous) @ blazor.server.js:10
(anonymous) @ blazor.server.js:1
e.invokeClientMethod @ blazor.server.js:1
e.processIncomingData @ blazor.server.js:1
connection.onreceive @ blazor.server.js:1
i.onmessage @ blazor.server.js:1
blazor.server.js:21 [2021-03-16T11:50:35.374Z] Error: System.AggregateException: One or more errors occurred. (TypeError: Cannot read property 'removeChild' of null)
 ---> System.InvalidOperationException: TypeError: Cannot read property 'removeChild' of null
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
   --- End of inner exception stack trace ---
``

Razor side
``
<RichTextEdit @ref="@this[Languagesitem.Key]"
                                                                              PlaceHolder=""
                                                                              ReadOnly="false"
                                                                              SubmitOnEnter="false"                                                                                
                                                                              ContentChanged="@(()=>{ EditorChanged(Languagesitem.Key,HTMLDescriptions); })"
                                                                              ToolbarPosition="Placement.Top">
                                                                    <Editor>
                                                                        @((MarkupString)HTMLDescriptions.Text)
                                                                    </Editor>
                                                                    <Toolbar>
                                                                        <RichTextEditToolbarGroup>
                                                                            <RichTextEditToolbarButton Action="RichTextEditAction.Bold" />
                                                                            <RichTextEditToolbarButton Action="RichTextEditAction.Italic" />
                                                                            <RichTextEditToolbarButton Action="RichTextEditAction.Underline" />
                                                                            <RichTextEditToolbarButton Action="RichTextEditAction.Strike" />
                                                                        </RichTextEditToolbarGroup>
                                                                        <RichTextEditToolbarGroup>
                                                                            <RichTextEditToolbarSelect Action="RichTextEditAction.Size">
                                                                                <RichTextEditToolbarSelectItem Value="small" />
                                                                                <RichTextEditToolbarSelectItem Selected="true" />
                                                                                <RichTextEditToolbarSelectItem Value="large" />
                                                                                <RichTextEditToolbarSelectItem Value="huge">Very Big</RichTextEditToolbarSelectItem>
                                                                            </RichTextEditToolbarSelect>
                                                                        </RichTextEditToolbarGroup>
                                                                        <RichTextEditToolbarGroup>
                                                                            <RichTextEditToolbarButton Action="RichTextEditAction.List" Value="ordered" />
                                                                            <RichTextEditToolbarButton Action="RichTextEditAction.List" Value="bullet" />
                                                                        </RichTextEditToolbarGroup>
                                                                        <RichTextEditToolbarGroup>
                                                                            <RichTextEditToolbarButton Action="RichTextEditAction.Blockquote" />
                                                                            <RichTextEditToolbarButton Action="RichTextEditAction.CodeBlock" />
                                                                        </RichTextEditToolbarGroup>
                                                                        <RichTextEditToolbarGroup>
                                                                            <RichTextEditToolbarSelect Action="RichTextEditAction.Color" />
                                                                            <RichTextEditToolbarSelect Action="RichTextEditAction.Background" />
                                                                        </RichTextEditToolbarGroup>
                                                                    </Toolbar>
                                                                </RichTextEdit>
``

C# side

``
private async void EditorChanged(string lang, MultilingualString multilingual)
        {
            multilingual.Text = await this[lang].GetHtmlAsync();           
        }
``

**Comment by mortezabarzkar** [comment] 2021-03-16 11:54
can you check it pls ?


Error
``
blazor.server.js:21 [2021-03-16T11:50:35.341Z] Error: There was an error applying batch 31.
e.log @ blazor.server.js:21
(anonymous) @ blazor.server.js:21
(anonymous) @ blazor.server.js:21
(anonymous) @ blazor.server.js:21
(anonymous) @ blazor.server.js:21
r @ blazor.server.js:21
e.processBatch @ blazor.server.js:21
(anonymous) @ blazor.server.js:10
(anonymous) @ blazor.server.js:1
e.invokeClientMethod @ blazor.server.js:1
e.processIncomingData @ blazor.server.js:1
connection.onreceive @ blazor.server.js:1
i.onmessage @ blazor.server.js:1
blazor.server.js:8 Uncaught (in promise) TypeError: Cannot read property 'removeChild' of null
    at e (blazor.server.js:8)
    at Object.e [as removeLogicalChild] (blazor.server.js:8)
    at e.applyEdits (blazor.server.js:8)
    at e.updateComponent (blazor.server.js:8)
    at Object.t.renderBatch (blazor.server.js:8)
    at e.<anonymous> (blazor.server.js:21)
    at blazor.server.js:21
    at Object.next (blazor.server.js:21)
    at blazor.server.js:21
    at new Promise (<anonymous>)
e @ blazor.server.js:8
e @ blazor.server.js:8
e.applyEdits @ blazor.server.js:8
e.updateComponent @ blazor.server.js:8
t.renderBatch @ blazor.server.js:8
(anonymous) @ blazor.server.js:21
(anonymous) @ blazor.server.js:21
(anonymous) @ blazor.server.js:21
(anonymous) @ blazor.server.js:21
r @ blazor.server.js:21
e.processBatch @ blazor.server.js:21
(anonymous) @ blazor.server.js:10
(anonymous) @ blazor.server.js:1
e.invokeClientMethod @ blazor.server.js:1
e.processIncomingData @ blazor.server.js:1
connection.onreceive @ blazor.server.js:1
i.onmessage @ blazor.server.js:1
blazor.server.js:21 [2021-03-16T11:50:35.374Z] Error: System.AggregateException: One or more errors occurred. (TypeError: Cannot read property 'removeChild' of null)
 ---> System.InvalidOperationException: TypeError: Cannot read property 'removeChild' of null
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
   --- End of inner exception stack trace ---
``

Razor side
``
<RichTextEdit @ref="@this[Languagesitem.Key]"
                                                                              PlaceHolder=""
                                                                              ReadOnly="false"
                                                                              SubmitOnEnter="false"                                                                                
                                                                              ContentChanged="@(()=>{ EditorChanged(Languagesitem.Key,HTMLDescriptions); })"
                                                                              ToolbarPosition="Placement.Top">
                                                                    <Editor>
                                                                        @((MarkupString)HTMLDescriptions.Text)
                                                                    </Editor>
                                                                    <Toolbar>
                                                                        <RichTextEditToolbarGroup>
                                                                            <RichTextEditToolbarButton Action="RichTextEditAction.Bold" />
                                                                            <RichTextEditToolbarButton Action="RichTextEditAction.Italic" />
                                                                            <RichTextEditToolbarButton Action="RichTextEditAction.Underline" />
                                                                            <RichTextEditToolbarButton Action="RichTextEditAction.Strike" />
                                                                        </RichTextEditToolbarGroup>
                                                                        <RichTextEditToolbarGroup>
                                                                            <RichTextEditToolbarSelect Action="RichTextEditAction.Size">
                                                                                <RichTextEditToolbarSelectItem Value="small" />
                                                                                <RichTextEditToolbarSelectItem Selected="true" />
                                                                                <RichTextEditToolbarSelectItem Value="large" />
                                                                                <RichTextEditToolbarSelectItem Value="huge">Very Big</RichTextEditToolbarSelectItem>
                                                                            </RichTextEditToolbarSelect>
                                                                        </RichTextEditToolbarGroup>
                                                                        <RichTextEditToolbarGroup>
                                                                            <RichTextEditToolbarButton Action="RichTextEditAction.List" Value="ordered" />
                                                                            <RichTextEditToolbarButton Action="RichTextEditAction.List" Value="bullet" />
                                                                        </RichTextEditToolbarGroup>
                                                                        <RichTextEditToolbarGroup>
                                                                            <RichTextEditToolbarButton Action="RichTextEditAction.Blockquote" />
                                                                            <RichTextEditToolbarButton Action="RichTextEditAction.CodeBlock" />
                                                                        </RichTextEditToolbarGroup>
                                                                        <RichTextEditToolbarGroup>
                                                                            <RichTextEditToolbarSelect Action="RichTextEditAction.Color" />
                                                                            <RichTextEditToolbarSelect Action="RichTextEditAction.Background" />
                                                                        </RichTextEditToolbarGroup>
                                                                    </Toolbar>
                                                                </RichTextEdit>
``

C# side

``
private async void EditorChanged(string lang, MultilingualString multilingual)
        {
            multilingual.Text = await this[lang].GetHtmlAsync();           
        }
``

**Comment by mortezabarzkar** [comment] 2021-03-16 12:42
@stsrki

**Comment by stsrki** [comment] 2021-03-16 12:47
I think @njannink can answer it better.

**Comment by mortezabarzkar** [comment] 2021-03-16 12:59
@njannink
it's like getting stuck in a loop

**Comment by njannink** [comment] 2021-03-16 15:07
@mortezabarzkar which version are you using? The removechild error I fixed in 0.9.3 unless this is a different variant

**Comment by mortezabarzkar** [comment] 2021-03-17 06:37
@njannink 
i used 0.9.2.5 version

**Comment by mortezabarzkar** [comment] 2021-03-17 06:39
because of #1979 . still use 0.9.2.5

**Comment by stsrki** [comment] 2021-03-17 06:48
@mortezabarzkar It must be that you miss something when migrating. Please follow the guide https://blazorise.com/news/release-notes/093/#migration-

And don't forget to follow https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio

**Comment by mortezabarzkar** [comment] 2021-03-17 07:04
i do all steps carefully , but still i have null referance error


[link](https://github.com/stsrki/Blazorise/issues/1979#issuecomment-792601459)

**Comment by stsrki** [comment] 2021-03-17 07:53
I fixed it and the patch will be released soon. During a day.

**Comment by mortezabarzkar** [comment] 2021-03-17 08:49
thank you

**Comment by stsrki** [comment] 2021-03-17 10:21
@mortezabarzkar NuGets released.

**Comment by mortezabarzkar** [comment] 2021-03-17 11:23
@njannink
now use 0.9.3.1 editor shown but when start to type "Test" it's shown "st"

**Comment by njannink** [comment] 2021-03-18 14:01
I will have a look this weekend or next week.

**Comment by njannink** [comment] 2021-03-26 21:42
I couldn't reproduce the loop myself, but I made some improvements. No more double events and I think I also broke the possible

**Closed** 2021-03-27 11:08 UTC
Labels: Area: RichTextEdit, Type: Bug 🐞
