### ISSUE TITLE
TextEdit jump caret to the end of the text for every typed char, when ChangeTextOnKeyPress is true.

### ISSUE THREAD

**Issue by ianido** [stsrki/Blazorise#733] opened 2020-04-14 18:40 UTC
- Version 0.8.8.4
- Material Design
- Google Chrome

If I have **options.ChangeTextOnKeyPress = true;**

The behavior of TextEdit jump the carent to the end of the text on every change, making impossible to edit the text properly (like insert letters at front or middle):
 
`<TextEdit @bind-Text="@this.Criteria.OpenDateFromText" />`

I Replaced temporarily by

`<input @bind-value="@this.Criteria.OpenDateFromText" @bind-value:event="oninput" class="form-control" />`

**Comment by WillianGruber** [comment] 2020-04-14 18:42
Happens to me too

**Comment by stsrki** [comment] 2020-04-14 19:54
This is the same problem as #655. It is also reported on https://github.com/dotnet/aspnetcore/issues/20067

Basically as Steve has mentioned, the problem is that Blazor needs to update component value. And by doing so browser will automatically refresh it and the cursor will move to the end.

It seems there is a workaround posted. I will try to see if it can be copied to Blazorise.

**Comment by stsrki** [comment] 2020-05-22 21:18
@ianido @WillianGruber Guys, I have started this ticket and now I'm trying to reproduce the bug but for me everything works. I would swear it was failing before. Coould be that Blazor team has changed somethings in latest version(s) and it's working now. Can you please check again if it works on your side?? Just make sure that you have latest version of Blazor 3.2 and Blazorise 0.9.0.3!

**Comment by WillianGruber** [comment] 2020-05-29 04:28
I'll try to reproduce it.

**Comment by stsrki** [comment] 2020-05-30 16:42
@WillianGruber Did you test it? If everything works I would close the issue.

**Comment by WillianGruber** [comment] 2020-05-30 18:07
I reproduced and the bug still happens:
Here you can see what happens when I try to type "asdfasdfasdfasdf":
![Test1](https://user-images.githubusercontent.com/56033692/83335995-d325ab00-a286-11ea-8ff1-0c1bdfa4c60e.gif)

This is what happens when I hold the "." key. It starts flickering and don't register all ".". In the end, when my mouse is circling I have already stopped pressing the "." key but it is still updating the field.
![Test2](https://user-images.githubusercontent.com/56033692/83336105-3a435f80-a287-11ea-8852-1d3bffd5f361.gif)

**Comment by WillianGruber** [comment] 2020-05-30 18:10
By the way, this only happens in a hard to render page. In this case, I have that old IconPicker I made.
I usually enclose it with "@if (Modal.Visible)" so I don't render the modal with all those icons unless the modal is really visible. This way, when editing other fields in the page, the problem above is mitigated.

**Comment by stsrki** [comment] 2020-05-30 21:52
@WillianGruber Thanks, I managed to reproduce it now.

**Closed** 2020-06-09 12:56 UTC
Labels: Status: Planning, Type: Feature Request ⛱
