### ISSUE TITLE
[Question] Button text colors for success and info

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#369] opened 2019-11-20 19:07 UTC
Is there a way to make the text color for success and info buttons white, just as the danger and secondary?

**Comment by stsrki** [comment] 2019-11-20 21:33
The easiest way is for you to define custom css rules.

If you're using theme provider the colors are calculated based on the background color. Maybe I can see what can be done to override the theme provider options.

**Comment by WillianGruber** [comment] 2020-01-21 14:33
@stsrki is it viable to include this in 0.9?

**Comment by stsrki** [comment] 2020-01-21 14:53
@WillianGruber I really don't know. The problem is that text color is calculated dynamically based on the background color. This is so that the right contrast is always applied and the text can re read at any time. For now I will leave it on backlog.

**Comment by WillianGruber** [comment] 2020-01-21 15:08
Sure, thanks!
________________________________

**Comment by stsrki** [comment] 2020-04-20 10:11
One way it add `Threshold `option for button theme options. That was we can handle when the color will switch from dark to light.

**Comment by stsrki** [comment] 2020-05-03 17:44
This is already fixed with the #832

I have started some refactoring on theme generator so this feature will be included anyway.

**Closed by stsrki** 2020-05-03 17:44 UTC
Labels: Type: Feature Request ⛱
