### ISSUE TITLE
TextEdit jump caret to the end of the text for every typed char, when ChangeTextOnKeyPress is true [2]

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#1053] opened 2020-06-30 14:43 UTC
Reopening TextEdit jump caret to the end of the text for every typed char, when ChangeTextOnKeyPress is true. #733
in a new issue.

Unfortunately the bug persists, just tested with 0.91

**Comment by stsrki** [comment] 2020-06-30 15:01
Try clearing the cache. Maybe you didn't get latest `blazorise.js` file.

**Comment by WillianGruber** [comment] 2020-06-30 15:17
I tried. Ctrl+F5 and Ctrl+shift+R on firefox.
When holding the "." key, it still flickers. Clicking the middle of "........................" and holding 'A' key, the first few A stay inside, but the later ones go to the end.
Result: ".........aa........aaaaaa". It behaves like the gif in #733

**Comment by stsrki** [comment] 2020-06-30 20:20
I'm trying it on SSB and I cannot reproduce it.

**Comment by WillianGruber** [comment] 2020-06-30 20:24
Sorry, what is SSB?

**Comment by stsrki** [comment] 2020-06-30 20:27
SSB = Server-Side Blazor.

Tested also on WebAssembly, and although it's somewhat slower it still works for me.

**Comment by FStolte** [comment] 2020-07-01 06:55
I can also reproduce the bug on 0.9.1 with Server-Side Blazor. I checked in Firefox and Chrome and made sure that the blazorise.js in the browser contains the setCaret and getCaret functions from the fix.

**Comment by stsrki** [comment] 2020-07-01 07:38
On my local machine everything just works. Now I have I tried it on the demo app that is located on the private server and on there it is not working. The problem as far as I can see, can only be reproduced on SSB apps.  I guess it is because SignalR and JSInterop are out of sync when you type too fast.

**Comment by cubed-it** [comment] 2020-07-01 13:03
Would it be a "solution", if instead of updating continuously, the whole thing would be delayed / throttled? Perhaps optional?

**Comment by stsrki** [comment] 2020-07-01 21:09
@cubed-it it might work. I will need to investigate it.

**Comment by stsrki** [comment] 2020-07-08 12:06
Note to self: https://www.freecodecamp.org/news/debounce-explained-how-to-make-your-javascript-wait-for-your-user-to-finish-typing-2/

**Comment by stsrki** [comment] 2020-07-08 21:03
@cubed-it I'm experimenting with delaying the input and I must say it works really great. And without any JavaScript. Now I need to find the right delay value so it's not too long or too short. But just in case I will also add a property to customize it.

**Closed** 2020-07-09 21:10 UTC
Labels: Type: Bug 🐞

**Comment by cubed-it** [comment] 2020-07-10 14:10
@stsrki that sounds great. bug fixed and perfromance improved! thanks a lot for your great work!
