### ISSUE TITLE
Numeric Format value in Charts Tooltip 

### ISSUE THREAD

**Issue by fantonifra** [stsrki/Blazorise#324] opened 2019-10-28 21:27 UTC
Numeric value in tooltip have a lot of decimal places. Is there some way to format the value?

![image](https://user-images.githubusercontent.com/19537867/67719198-aac48e00-f9d1-11e9-8942-4a8c09294f86.png)

**Comment by stsrki** [comment] 2019-10-29 08:23
According to the documentation it can only be done by settings the label callback on options https://www.chartjs.org/docs/latest/configuration/tooltip.html#label-callback

The problem is that we currently don't support callbacks from JavaScript . @andrewwilkin has started some work on #313 to make callbacks between JavaScript and Blazor that can be used to format the values. I don't how much work he's done.

**Comment by andrewwilkin** [comment] 2019-10-31 18:27
@fantonifra the easiest way of doing that would be to round the data before sending it to the chart if you can live with that.

There is no way of wiring up the callbacks into Blazor due to the way the interop returns a promise. I have spent a fair bit of time trying various approaches and not got anywhere.

My current thinking is to extend the object that is passed in, as ChartJS does not complain about properties in the object it does not use from my testing and use that to define what JavaScript callback options should be wired in.

Note also that as @stsrki has mentioned, with the current serializer not able to ignore null properties the JSON options are preferable if you plan to leverage ChartJS features.

**Comment by stsrki** [comment] 2019-11-29 12:22
Closing for now as there is currently no easy way to handle this. @andrewwilkin workaround is the best solution for now.

**Closed by stsrki** 2019-11-29 12:22 UTC
