### ISSUE TITLE
Enhancement: BreakpointActivator with multiple breakpoints

### ISSUE THREAD

**Issue by njannink** [stsrki/Blazorise#1895] opened 2021-02-22 19:52 UTC
I like the concept of the `BreakpointActivatorAdapter`, but I need to handle multiple breakpoints (mobile, tablet and desktop) and the current adaptar only has support for a single breakpoint. Maybe we could extend this with IBreakpointNotification or something so I can get notified on each breakpoint?

**Comment by stsrki** [comment] 2021-02-22 20:12
Duplicate of #1036

Unfortunately, @MitchellNZ didn't have too much time to work on this feature so I will move to the next mileston since the new release is planned for this week.

**Closed by stsrki** 2021-02-22 20:12 UTC
