### ISSUE TITLE
Validation is not working well with data object populated async

### ISSUE THREAD

**Issue by jllh** [stsrki/Blazorise#499] opened 2020-01-11 20:38 UTC
Hello,

Great job at wrapping bootstrap in blazor components.

I would like to point out that validation isn't working correctly when we are using async to populate the object binded to editors.

When loading a page for the first time, validator have a mistaken Status. If we navigate to another page and come back, all is fine. If we load the page from the browser adress bar, then the incorrect behavior reappear.

I have noted some incorrect behaviors. All of which seems to appear only if we use an async method to populate the data object.

The validation status is linked to the first value asigned, but when the async method change that value, the validation status is not changed accordingly.

With Validator property, only the initial status is incorect. If we change the value in the EditComponent, the validation behaves correctly. But with DataAnnotation, the validation status stay the same while editing, until we change page and return to this one.

Here is my cases:
If you comment one handler OnInitialized() or OnInitializedAsync(), you can see the different behaviors.

```
@page "/testpage"

@using BlazorApp2.Data

@inject TestService TestService

<h3>TestPage</h3>

<Validations Mode="ValidationMode.Auto">
    <Field IsHorizontal="true">
        <FieldLabel ColumnSize="ColumnSize.Is2">Name</FieldLabel>
        <FieldBody ColumnSize="ColumnSize.Is10">
            <Validation Validator="@ValidationRule.IsNotEmpty">
                <TextEdit Placeholder="Name ..." @bind-Text="@TestObject.Name">
                    <Feedback>
                        <ValidationError>Error!</ValidationError>
                    </Feedback>
                </TextEdit>
            </Validation>
        </FieldBody>
    </Field>
</Validations>

<Validations Mode="ValidationMode.Auto" Model="@TestObject">
    <Field IsHorizontal="true">
        <FieldLabel ColumnSize="ColumnSize.Is2">Name</FieldLabel>
        <FieldBody ColumnSize="ColumnSize.Is10">
            <Validation Validator="@ValidationRule.IsNotEmpty">
                <TextEdit Placeholder="Name ..." @bind-Text="@TestObject.Name">
                    <Feedback>
                        <ValidationError />
                    </Feedback>
                </TextEdit>
            </Validation>
        </FieldBody>
    </Field>
</Validations>

@code {
    public TestObject TestObject { get; set; } = new TestObject();

    //protected override void OnInitialized()
    //{
    //    TestObject = TestService.GetTestObject();

    //    base.OnInitialized();
    //}

    protected override async Task OnInitializedAsync()
    {
        TestObject = await TestService.GetTestObjectAsync();

        await base.OnInitializedAsync();
    }
}

```

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlazorApp2.Data
{
    public class TestService
    {
        private ApplicationDbContext _db;

        public TestService(ApplicationDbContext db)
        {
            _db = db;
        }

        public TestObject GetTestObject()
        {
            return _db.TestObject.Find(1);
        }

        public async Task<TestObject> GetTestObjectAsync()
        {
            return await _db.TestObject.FindAsync(1);
        }
    }
}
```
```

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BlazorApp2.Data
{
    public class TestObject
    {
        public int Id { get; set; }
        [StringLength(10, ErrorMessage = "Error!")]
        public string Name { get; set; }
    }
}

```
Note that this does this only when assing the dataobject property like shown. If we don't initialize the data object property, and if we enclose validation in an 'if', it is working.

```
@if (TestObject is null)
{
    <span>Loading...</span>
}
else
{
    Validation...
}
```
It is maybe just a Blazor behavior. Maybe assigning value directly to the data object property isn't supported.

**Comment by jllh** [comment] 2020-01-12 02:58
After a few try, I noticed that it has to do with assigning the data object more than one time in conjunction with async and DataAnnotation. In fact, If I assign the object twice in the OnInitializedAsync, the validation breaks and stay to the status of the value of the first assignation.

```
    <Validations Mode="ValidationMode.Auto" Model="@TestObject">
        <Field IsHorizontal="true">
            <FieldLabel ColumnSize="ColumnSize.Is2">Name</FieldLabel>
            <FieldBody ColumnSize="ColumnSize.Is10">
                <Validation>
                    <TextEdit Placeholder="Name ..." @bind-Text="@TestObject.Name">
                        <Feedback>
                            <ValidationError />
                        </Feedback>
                    </TextEdit>
                </Validation>
            </FieldBody>
        </Field>
    </Validations>
```

```
    protected override async Task OnInitializedAsync()
    {
        TestObject = new TestObject() { Name = "breakingTest" };

        TestObject = await TestService.GetTestObjectAsync();

        await base.OnInitializedAsync();
    }
```

**Comment by jllh** [comment] 2020-01-12 04:12
It does the same thing when I navigate to the same page with a different route parameter. When the data object is assigned for the second time, since the page isn't initiated a second time, validation breaks, and stay always the same (the one of the first pass). I have to set the data object to null, before the second assignation, to get the validation to works.

`@page "/testpage/{Id:int}"`

`<a href="/testpage/2">link</a>`

```
[Parameter]
    public int? Id { get; set; }
```

```
   public async override Task SetParametersAsync(ParameterView parameters)
    {
        await base.SetParametersAsync(parameters);
        if (Id is null) Id = 1;
    }

    protected override void OnInitialized()
    {
        base.OnInitialized();
        if (Id is null) Id = 1;
    }
```

```
protected override async Task OnParametersSetAsync()
    {
        await base.OnParametersSetAsync();

        if (TestObject is null || TestObject.Id != Id)
        {
            //TestObject = null;  //this line can solve the problem
            if (Id == 0)
            {
                TestObject = new TestObject () { Id = -1, Name = "" };
            }
            else
            {
                TestObject = await TestService.GetTestObjectAsync((int)Id);
            }
        }
    }
```

After a search it seems to be a duplicate of issue #320 but still a problem in 8.8.

**Comment by valentasm1** [comment] 2020-06-08 10:37
Is there any workarounds ?

**Comment by StefanStsc** [comment] 2020-08-18 09:25
@valentasm1  I've the same problem and managed to workaround this by using the key-Attribute on the Validations like this:

`<Validations Mode="@Mode" ValidateOnLoad="false" Model="@Model" @ref="_validations" @key="@Model.GetHashCode()">
<other elements/>
</Validations>`

This will replace the whole tree whenever the model reference changes.

**Comment by stsrki** [comment] 2020-12-01 12:03
This should be fixed in the latest version. Please reopen if the error is still present.

**Closed by stsrki** 2020-12-01 12:03 UTC
Labels: Status: Investigate, Type: Bug 🐞

**Comment by WayneHiller** [comment] 2022-04-21 18:30
@stsrki This seems to be happening in version 1.0.4 again. I was able to work around it by adding a @key attribute to the Validations. In my case I have a Model form where the user can click an "Add New" btn to save the current record and create a new one ready to edit. The initial validation works but once a new object is bound to the editors it stops working.

**Comment by stsrki** [comment] 2022-04-21 18:33
This is an old ticket that might not be valid any more. Can you open new ticket with code to reproduce the issue?

**Comment by muipsd** [comment] 2022-04-23 19:01
Confirming 1.0.4 has this problem.
