### ISSUE TITLE
Add support for MS Fluent UI Fabric Core

### ISSUE THREAD

**Issue by PlastMan420** [stsrki/Blazorise#1049] opened 2020-06-30 04:33 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: I am trying to do [...] but [...]
Add support for MS Fluent UI Fabric Core
**Describe the solution you'd like**
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

**Comment by stsrki** [comment] 2020-06-30 08:26
Duplicate of #94 

Having new provider requires too much time and resources. For now I don't have it in plan any time soon. Maybe after version 1.0 when API stabilizes I can start looking into it.

**Closed by stsrki** 2020-06-30 08:26 UTC
