### ISSUE TITLE
Snackbar won't work on the page with Authorize attribute

### ISSUE THREAD

**Issue by MuhammedBalta** [stsrki/Blazorise#1314] opened 2020-09-16 19:48 UTC
**Describe the bug**
Snackbar won't work on the page with Authorize attribute. This issue occurs only the first load of the page. Snackbar starts working after refreshing the page
```

@page "/"
@attribute [Authorize]
<Button Clicked="@(()=>snackbar.Show())">Snackbar</Button>

<Snackbar @ref="snackbar">
    <SnackbarBody>
        Message
    </SnackbarBody>
</Snackbar>
@code{
    Snackbar snackbar;
}
```

**Comment by stsrki** [comment] 2021-04-12 19:58
Closing because I was unable to reproduce it.

**Closed by stsrki** 2021-04-12 19:58 UTC
