### ISSUE TITLE
RadioGroup-event or binding doesnt work when Buttons="true"

### ISSUE THREAD

**Issue by JamesB49** [stsrki/Blazorise#908] opened 2020-05-20 07:16 UTC
**Describe the bug**
The issue is close to the one previously reported #859 
The RadioGroup works properly when using either Events or Bind Attribute. But when I set _Buttons="true"_ it just doesn't work anymore. The event is not called (breakpoint never reached, and object value never changed).

```
<RadioGroup TValue="int" Name="filterStatus" CheckedValue="@_filter" CheckedValueChanged="OnFilterStatusValueChanged" Buttons="true">
    <Radio TValue="int" Value="0" title="All">所有</Radio>
    <Radio TValue="int" Value="1" title="Opened">进行中</Radio>
    <Radio TValue="int" Value="2" title="Closed">完整</Radio>
</RadioGroup>

@_filter

@code 
{
int _filter = 0;

void OnFilterStatusValueChanged(int value)
    {
        _filter  = value;
    }
}
```

**Expected behavior**
A similar behavior regardless of the "Buttons" option.

**Additional context**
Let me know if there's anymore information needed to help understand/solve the problem. Perhaps (luckily?) the issue is just on my side and I missed something?
Thank you very much!
J.

**Comment by stsrki** [comment] 2020-05-20 08:05
I found the problem. My guess is you're using Bootstrap provider? In that case the problem is with RadioGroup component. I render it with `data-toggle` attribute. Like this:

```
<div class="@ClassNames" style="@StyleNames" @attributes="@Attributes" data-toggle="buttons">
    @ChildContent
</div>
```

It seems that bootstrap js is interfering with `data-toggle` and because of that events are not handled. I will fix it and release it as part of next patch. In the meantime you can remove `bootstrap.min.js` as a workaround. That is if you don't need it.

**Comment by JamesB49** [comment] 2020-05-20 08:17
wow! thank you so much for such a quick answer!

The workaround work perfectly!

I really love your work with Blazorise. I'm new to the whole tech, but it's really great to use!

I guess I will let you close the ticket when the fix is deployed?
Cheers,
James

**Comment by stsrki** [comment] 2020-05-20 08:24
No problem!

When I fix the issue I will close it. tnx

**Closed** 2020-05-21 14:20 UTC
Labels: Area: Bootstrap, Priority: High ⚡, Type: Bug 🐞, Type: Quick Fix
