### ISSUE TITLE
[Bug] Scrolling long modal - only Firefox

### ISSUE THREAD

**Issue by gaffkins** [stsrki/Blazorise#877] opened 2020-05-11 19:18 UTC
When you try scrolling long modal on Firefox scrolling not work.
Sometimes, very rare it's work on first try.
On Safari and Chrome everything work fine.

1. Go to https://bootstrapdemo.blazorise.com/tests/modals
2. Click on 'Centered Modal' button
3. Minimalize browser height to cut modal
4. Try scroll modal (work only when cursor is on close button)

**Comment by stsrki** [comment] 2020-05-11 22:01
I can confirm the bug. After further investigation I found out the problem is in the backdrop placement. Instead if placing it inside of Modal I should place it outside of it(specifically after the modal `<div>` element).

The change will possibly be a breaking change. So because of that I will do it as part of v0.9.2

**Comment by StefanOssendorf** [comment] 2020-08-10 08:41
I can reproduce the behvior with Chrome, too. At the moment only scrolling with the mouse-wheel is possible since the browser-scrollbar is "hidden" by the backdrop.

**Comment by stsrki** [comment] 2020-11-09 08:45
Ther's no time to finish it for this milestone so moving to next

**Closed** 2021-02-11 09:54 UTC
Labels: Priority: High ⚡, Type: Breaking Change 💔, Type: Bug 🐞
