### ISSUE TITLE
Problem in DataGrid when number of page more than 20

### ISSUE THREAD

**Issue by Saeidasadi32** [stsrki/Blazorise#329] opened 2019-11-04 08:43 UTC
Hi
I have data table with over than 1000 record and in set page zise to 10
after run app , width of page is very large
please help me
Thank you
Saeid.

**Comment by stsrki** [comment] 2019-11-04 11:25
Hi, can you give me more information? Maybe post a screenshot?

**Comment by Saeidasadi32** [comment] 2019-11-04 13:27
Hi
i sent a screenshot 
![grid](https://user-images.githubusercontent.com/56113717/68124235-1d7abf80-ff24-11e9-9a38-05badc1661ba.jpg)

**Comment by stsrki** [comment] 2019-11-04 13:30
I guess you have only one `Column `defined so it's filling the entire grid. Please also post the sample code for your `DataGrid `so I can have a look.

**Comment by Saeidasadi32** [comment] 2019-11-04 13:42
I used 3 column 
                        <DataGrid TItem="Company"
                                  Data="@companies"
                                  AllowSort=true
                                  AllowFilter=true
                                  ShowPager=true
                                  PageSize="10"
                                  UseInternalEditing="true"
                                  IsStriped="true"
                                  IsBordered="true"
                                  IsHoverable="true">
                            <ChildContent>
                                <DataGridCommandColumn TItem="Company">
                                    <NewCommandTemplate>
                                    </NewCommandTemplate>
                                    <EditCommandTemplate>
                                    </EditCommandTemplate>
                                    <SaveCommandTemplate>
                                    </SaveCommandTemplate>
                                    <DeleteCommandTemplate>
                                    </DeleteCommandTemplate>
                                    <CancelCommandTemplate>
                                    </CancelCommandTemplate>
                                    <ClearFilterCommandTemplate>
                                        <Button Color="Color.Warning" Clicked="@context.Clicked">حذف فیلتر</Button>
                                    </ClearFilterCommandTemplate>
                                </DataGridCommandColumn>
                                <DataGridColumn TItem="Company" Field="@nameof(Company.CNamad)" Caption="نماد "/>
                                <DataGridColumn TItem="Company" Field="@nameof(Company.CName)" Caption="نام شرکت"/>
                                <DataGridSelectColumn TItem="Company" Field="@nameof( Company.CGroup )" Caption="گروه صنعت">
                                    <DisplayTemplate>
                                        @{
                                            var cgroup = (context as Company)?.CGroup;
                                            @(companyGroups.Find(x => x.GID == cgroup).GName)
                                        }
                                    </DisplayTemplate>
                                </DataGridSelectColumn>
                            </ChildContent>
                        </DataGrid>

**Comment by stsrki** [comment] 2019-11-04 17:05
I'm really sorry but I don't see any razor code. All I see is this (screenshot bellow):

![image](https://user-images.githubusercontent.com/900302/68141356-a64a2900-ff2d-11e9-9cac-c481bf9b52b0.png)

**Comment by Saeidasadi32** [comment] 2019-11-04 19:11
@page "/ACompany"
@inject HttpClient Http

    <Row>
        <Column>
            <Card Margin="Margin.Is4.OnY">
                <CardHeader Class="text-center">
                    <CardTitle><h4>اطلاعات شرکت های بورسی</h4></CardTitle>
                </CardHeader>
                <CardBody>
                    <Row>
                        <Column>
                            <Card>
                                <CardHeader Class="text-center">
                                    <CardTitle><h5>تعریف یا تصحیح اطلاعات شرکت های بورسی</h5></CardTitle>
                                </CardHeader>
                                <CardBody>
                                    <Fields Class="frtl">
                                        <Field ColumnSize="ColumnSize.Is6.OnDesktop">
                                            <FieldLabel>نماد</FieldLabel>
                                            <TextEdit Placeholder="عنوان نماد فارسی">
                                            </TextEdit>
                                        </Field>
                                        <Field ColumnSize="ColumnSize.Is6.OnDesktop">
                                            <FieldLabel>نام شرکت</FieldLabel>
                                            <TextEdit Placeholder="نام فارسی شرکت">
                                            </TextEdit>
                                        </Field>
                                        <Field ColumnSize="ColumnSize.Is6.OnDesktop">
                                            <FieldLabel>نام لاتین نماد</FieldLabel>
                                            <TextEdit Placeholder="نام لاتین نماد ">
                                            </TextEdit>
                                        </Field>
                                        <Field ColumnSize="ColumnSize.Is6.OnDesktop">
                                            <FieldLabel Class="Color.Success">نام لاتین شرکت</FieldLabel>
                                            <TextEdit Placeholder="نام لاتین شرکت">
                                            </TextEdit>
                                        </Field>
                                        <Field ColumnSize="ColumnSize.Is6.OnDesktop">
                                            <FieldLabel>عنوان گروه صنعت</FieldLabel>
                                            <SelectList Data="@companyGroups"
                                                        TextField="@((item)=>item.GName)"
                                                        ValueField="@((item)=>item.GID)"
                                                        SelectedValue="@selectedListValue"
                                                        SelectedValueChanged="@MyListValueChangedHandler" />
                                        </Field>
                                        <Field ColumnSize="ColumnSize.Is6.OnDesktop">
                                            <FieldLabel>عنوان بازار</FieldLabel>
                                            <SelectList Data="@tablos"
                                                        TextField="@((item)=>item.BName)"
                                                        ValueField="@((item)=>item.BTID)"/>
                                        </Field>
                                    </Fields>
                                </CardBody>
                                <CardFooter Class="text-center Color.Success">
                                    <Button Color="Color.Success">جدید</Button>
                                    <Button Color="Color.Primary">ذخیره</Button>
                                    <Button Color="Color.Danger">حذف</Button>
                                </CardFooter>
                            </Card>
                        </Column>
                    </Row>
                </CardBody>
                @if (companyGroups == null)
                {
                    <CardBody class="text-center">
                        <img height="100" src="../../imag/loadingl.jpg" />
                    </CardBody>
                }
                else
                {
                    <CardBody Class="frtl">
                        <DataGrid TItem="Company"
                                  Data="@companies"
                                  AllowSort=true
                                  AllowFilter=true
                                  ShowPager=true
                                  PageSize="100"
                                  IsBordered="true"
                                  IsHoverable="true">
                            <ChildContent>
                                <DataGridCommandColumn TItem="Company">
                                    <ClearFilterCommandTemplate>
                                        <Button Color="Color.Warning" Clicked="@context.Clicked">حذف فیلتر</Button>
                                    </ClearFilterCommandTemplate>
                                </DataGridCommandColumn>
                                <DataGridColumn TItem="Company" Field="@nameof(Company.CNamad)" Caption="نماد " Class="font-weight-bold" />
                                <DataGridColumn TItem="Company" Field="@nameof(Company.CName)" Caption="نام شرکت" />
                                <DataGridSelectColumn TItem="Company" Field="@nameof( Company.CGroup )" Caption="گروه صنعت">
                                    <DisplayTemplate>
                                        @{
                                            var cgroup = (context as Company)?.CGroup;
                                            @(companyGroups.Find(x => x.GID == cgroup).GName)
                                        }
                                    </DisplayTemplate>
                                </DataGridSelectColumn>
                                <DataGridSelectColumn TItem="Company" Field="@nameof( Company.BGroup )" Caption="عنوان بازار">
                                    <DisplayTemplate>
                                        @{
                                            var bgroup = (context as Company)?.BGroup;
                                            @(tablos.Find(x => x.BTID == bgroup).BName)
                                        }
                                    </DisplayTemplate>
                                </DataGridSelectColumn>
                            </ChildContent>
                        </DataGrid>
                    </CardBody>
                }
            </Card>
        </Column>
    </Row>

@code {
    List<CompanyGroup> companyGroups;
    List<Company> companies;
    List<Tablo> tablos;

    protected override async Task OnInitializedAsync()
    {
        companies = await Http.GetJsonAsync<List<Company>>("api/Companies");
        
        tablos = await Http.GetJsonAsync<List<Tablo>>("api/Tabloes");
        companyGroups = await Http.GetJsonAsync<List<CompanyGroup>>("api/CompanyGroups");
    }

        object selectedListValue { get; set; } = 3;

    void MyListValueChangedHandler( object newValue )
    {
        selectedListValue = newValue;
        StateHasChanged();
    }
}

**Comment by stsrki** [comment] 2019-11-04 19:24
OK now I realize what's happening. The problem is in the code responsible for pagination. When it generates the pagination buttons it will calculate how many buttons it needs. In your case it will be, 1000 records divided by 10 (page size) equals 100 buttons. Needles to say, it's not working as expected. I didn't thought much how it should behave for large data sources.

Anyways, I will try to fix this, probably in the v0.8.8.

**Comment by ricardoromaobr** [comment] 2019-12-04 17:53
In my pull request I already made it.

**Comment by ricardoromaobr** [comment] 2019-12-04 18:00
I Aad VisibleLinkPage, that take the number of link to be showed in the navigation
page.

**Comment by ricardoromaobr** [comment] 2019-12-04 18:01
The default link showed is 5, but user would define a value that he want

**Comment by ricardoromaobr** [comment] 2019-12-04 18:09
![Untitled](https://user-images.githubusercontent.com/7851330/70168661-0efd0080-16a8-11ea-8d16-03019a874563.png)

**Comment by stsrki** [comment] 2019-12-06 13:32
@ricardoromaobr 

I merged your code and modified pagination to be more user-friendly. Now when user clicks on page link, the first and last page will be calculated based on the offset and max pagination links.

**Closed by stsrki** 2019-12-06 13:32 UTC
Labels: bug
