### ISSUE TITLE
Multi-select in DataGrid checkbox does not uncheck if row selected 

### ISSUE THREAD

**Issue by wmachanik** [stsrki/Blazorise#1859] opened 2021-02-17 12:21 UTC
With DataGrid 0.9.3 preview and SelectionMode="DataGridSelectionMode.Multiple" when a row is clicked on the check box for the selected is ticked. If you try  and unselect that check box it resellects it

**To Reproduce**
1. Go to DataGrid with SelectionMode="DataGridSelectionMode.Multiple" 
2. Click on a row in the grid
3. Checkbox for multi-select is checked.
4. If you then try and uncheck it, it remains checked.

**Expected behavior**
If you click on the check box it should un-select even if that row is selected.

I used the code from: https://github.com/stsrki/Blazorise/blob/dev093/Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor

1. Datagrid test a per above
2. when screen loads change Selection mode to Multiple
3. Click any row, check box changes to ticked
4. Click Checkbox - checks and unchecks

**Screenshots**
Can send but need a video

**Additional context**
na

**Comment by stsrki** [comment] 2021-02-17 12:24
@David-Moreira can you please have a look at this once you have time?

**Comment by David-Moreira** [comment] 2021-02-17 12:52
Yea I'll see if I have time later today.

**Comment by David-Moreira** [comment] 2021-02-17 22:20
Ok so the checkboxes behave separately from the row clicks. They only change the **SelectedRows** collection Parameter .
However their boolean also checks for **SelectedRow** Parameter just to make sure it always displays what's selected.

**Which means whenever I click the checkbox, it currently does not update the SelectedRow.** And this was originally intended...
I have fixed it, so that it if the last checked item is unchecked by the user and the **SelectedRow** is the same as the item being unchecked, it now correctly sets **SelectedRow** to null and fixes it.


So the following can happen, I can select a checkbox which will fill the **SelectedRows** collection Parameter, but will not update the **SelectedRow** Parameter and like I said this was intended...
![image](https://user-images.githubusercontent.com/22283161/108274281-924f2880-716c-11eb-9aa3-53b57298c838.png)

But I was now thinking if it actually makes sense or not, @stsrki  what do you think?
1 - Should we update **SelectedRow** to the last clicked checkbox? Does that make sense?
2 - Should we keep the current behaviour, but with this fix?

**Comment by stsrki** [comment] 2021-02-17 22:36
@David-Moreira 

As I recall, `SelectedRows` and `SelectedRow` were separated depending on `DataGridSelectionMode.Single` or `DataGridSelectionMode.Multiple`. If we're separating them like that then it makes sense to not update `SelectedRow`.

But, I think it makes sense from UX perspective. Each time `check=true` we should also update `SelectedRow`. But in that case we should track what is the last checked item. Meaning if you have checked 5 items and you **un**check no. 5, then no. 4 would be set onto `SelectedRow`. It could get complicated pretty fast...

Can you create a PR with the fix so I can see it in action? Maybe I'm missing something.

**Comment by David-Moreira** [comment] 2021-02-17 22:48
Hmm I guess that makes sense. The tracking also seems to make sense. Not sure if worth having another in memory collection to track it...
Alright I'll PR in a bit.

**Comment by David-Moreira** [comment] 2021-02-17 23:00
I was thinking about this, you're kinda right here:
"As I recall, `SelectedRows `and `SelectedRow `were separated depending on `DataGridSelectionMode.Single` or `DataGridSelectionMode.Multiple`. If we're separating them like that then it makes sense to not update SelectedRow."

When on `DataGridSelectionMode.Multiple`. We're still updating SelectedRow on normal row clicks, and maybe it just makes sense to make the clear distinction between both modes, and have it set to null on `DataGridSelectionMode.Multiple` and never ever update it on this mode.

Otherwise, we can go with the second option you were talking about, and keep updating whether its row click or checkbox click.
But is there really a use case where someone wants to track `SelectedRow `when `DataGridSelectionMode.Multiple` is on?
Even if the user would like to grab the last selected row, that should just be grabbing the last record out of `SelectedRows`

**Comment by stsrki** [comment] 2021-02-18 08:58
I think it's best to separate them. For example, a `Select` component also has a `Multiple` mode and both `SelectedValue` and `SelectedValues` are strictly separated.

But then again it still makes sense to have `SelectedRow` when multiple modes is on and the last selected item is focused. Although maybe the naming here is not best. It should be named `FocusedRow`. But I'm not sure if introducing additional API makes sense.

**Comment by stsrki** [comment] 2021-02-18 09:13
PS. your modification in PR seems to work nicely now.

**Comment by David-Moreira** [comment] 2021-02-18 12:16
I actually see the use for the focused row. I have a project where I use a main grid and then there's a "slave" grid which loads records according to the main grid selected row. 
So if I wanted to have multiple selection on the main grid and still load related items to a focused row on the "slave" grid, that would be helpful. However I think its just ends up being more confusing, because then you have to be able to actually tell the focused row apart from the others... 


But for now... I'm in favor of strictly separating selected row and selected rows. Is that okay with you? 

The PR I submitted solves this issue, would you like to close it, or could I do the strict separation as part of the PR?

**Comment by stsrki** [comment] 2021-02-18 12:46
I will accept the PR. It's useful and whatever we try to come up with, every scenario makes sense. So it's best to have SelectedRow in multiple mode also. As you already said, there are use cases for it.

Going out now, but I will merge it as soon as I got back.

**Closed** 2021-02-18 14:45 UTC
Labels: Type: Bug 🐞
