### ISSUE TITLE
Non-displayable DataGridColumns are displayed when editing

### ISSUE THREAD

**Issue by mnelvers** [stsrki/Blazorise#1249] opened 2020-08-13 17:43 UTC
**Describe the bug**
We have a DataGrid with eight columns (misture of DataGridColumn and DataGridNumericColumn objects).  The DataGrid has the EditMode="DataGridEditMode.Inline" attribute set.  Only one of the columns is editable.  Four of the other columns have a Displayable="false" attribute.  Those columns are not displayed normally, but when a rows is edited (in InLine mode), the non-displayable data is displayed.  If the non-displayable columns are before the displayable column, the data is displayed in the wrong positions. 

**To Reproduce**
Create a DataGrid with several columns.
Set the DataGrid to use in-line editing (EditMode="DataGridEditMode.Inline").
Mark some of the columns asnon-displayable (Displayable="false").
Set only one of the displayable columns to be editable.
Add some data to the DataGrid.
Edit one of the rows.

**Expected behavior**
Only displayable columns should be displayed in the edit row.

This is the row before edit is clicked:
![Original](https://user-images.githubusercontent.com/44039733/90168226-c9cabb80-dd6a-11ea-847b-546e028614f8.JPG)

This is the same row after the edit button is clicked.  Note the extra data at the end of the row.
![Editing](https://user-images.githubusercontent.com/44039733/90168324-eebf2e80-dd6a-11ea-9c6e-253d02a297dd.JPG)

If the non-displayable columns were positioned before the displayable columns, the extra data would have been displayed before the displayable data, but the column headings would have remained in the same position.

**Comment by Jinjinov** [comment] 2020-09-22 18:07
This is duplicate of https://github.com/stsrki/Blazorise/issues/1223

**Closed** 2020-09-22 19:29 UTC
Labels: Type: Bug 🐞
