### ISSUE TITLE
Autoplay="false" not working all the time

### ISSUE THREAD

**Issue by BrianHeredia** [stsrki/Blazorise#1751] opened 2021-01-26 19:21 UTC
Hi,

I'm using a Blazorise Carousel on my Blazor Server project and setting the Autoplay to false, but this does not work all the time. My code is this:

`<Carousel @bind-SelectedSlide="@selectedSlide" ShowIndicators="false" Autoplay="false"  AutoplayInterval="10000000">
   ...
</Carousel>`

When I use the Inspector I see that the Bootstrap Carousel reproduces as follow:

`<div class="carousel slide" data-ride="carousel"></div>`

When the   BootStrap documentation: [https://getbootstrap.com/docs/4.0/components/carousel/#options](url)  says that in order to Carousel not autoplay it should have the data-interval set to false like this:

`<div class="carousel slide" data-ride="carousel" data-interval="false">`

I don't understand on what it depends for it to work properly.

**Comment by stsrki** [comment] 2021-01-26 22:52
I've just tried `Autoplay="false"` and it seems it's working.

Are you setting `Autoplay` dynamically or just once when the page is initialized?

**Comment by BrianHeredia** [comment] 2021-01-27 04:43
I'm setting it one time, not dinamically.

As I said, almost always works, but sometimes just for a while, and the it starts autoplaying.

**Comment by stsrki** [comment] 2021-01-27 08:30
It's hard to tell what's wrong when it is not consistent. Maybe it's something with SignalR connection when you use server-side Blazor 🤔.

I tested with Chrome, Firefox, and Edge and they all work just fine.

**Comment by stsrki** [comment] 2021-04-07 10:35
Closing since I was not able to reproduce.

**Closed by stsrki** 2021-04-07 10:35 UTC

**Comment by BrianHeredia** [comment] 2021-05-08 19:53
I would like you to reopen this Issue as it continuos to happen, even in production. If you could email me to brianheredia@gmail.com I would send you the link to a live sample where is doesn't work properly

**Comment by AlexTeixeira** [comment] 2021-06-08 12:08
Hi @BrianHeredia,

I'm working with a carousel this day and I has the same issue when I start playing with the component.

I don't know if this helps, but it seems that the carousel has a rendering problem when you have too many components/items drawn asynchronously at the same time.
To avoid this, just check if your data are filled before render the carousel.

@stsrki when the carousel wasn't working, I had multiple Task.Canceled if it can help you to investigate

**Comment by BrianHeredia** [comment] 2021-06-09 13:52
Hi @AlexTeixeira,

> To avoid this, just check if your data are filled before render the carousel.

I'm filling data OnParameterSetAsync for the component containing de Carousel,  are you suggesting using OnInitializeAsync instead?

**Comment by stsrki** [comment] 2021-06-09 13:54
It is always better in OnInitializeAsync than OnParameterSetAsync. The problem with OnParameterSetAsync is that it is called every time something changes on a page.

**Comment by BrianHeredia** [comment] 2021-06-09 15:44
Thanks @stsrki, I'm gonna take that into account.

**Comment by adamhathcock** [comment] 2021-09-12 12:30
I also have this issue.

I believe it could be solved by simply checking `Autoplay` for false just like `AutoRepeat` is checked in the timer event.

I wish this was false by default

**Comment by stsrki** [comment] 2021-09-12 12:33
@adamhathcock What version are you using? We have done major refactoring on the Carousel component in the latest 0.9.4.x so this should probably we fixed.

**Comment by adamhathcock** [comment] 2021-09-12 12:51
I'm using 0.9.4.4

The issue seems to be dealing with loading the Carousel or it's slides dynamically, which is what i'm doing.  The timer gets started at some point.

I think I can make it work by doing `_carousel.Timer.Stop();` on a callback on the `SelectedSlideChanged` to ensure the timer is really not going.
