### ISSUE TITLE
Validations.ClearAll() Fails to clear validations for second field

### ISSUE THREAD

**Issue by brettwinters** [stsrki/Blazorise#222] opened 2019-08-28 03:34 UTC
Hello

I also encountered this issue also #186 (I have another issue where the validation handler ValidatorEventArgs e.Value seems to use the wrong (ie previous model value when navigating to a new record) value to validate which I will raise separately - but I think it's related)

```html
<Validations @ref="validations" @ref:suppressField Mode="ValidationMode.Manual">
    <Validation Validator="ValidateName">
        <Field>
            <FieldLabel>Name</FieldLabel>
                <TextEdit Text="@Organisation.Name">
                    <ValidationError></ValidationError>
                </TextEdit>
        </Field>
    </Validation>

    <Validation Validator="ValidateDescription">
        <Field>
            <FieldLabel>Description</FieldLabel>
                <TextEdit Text="@Organisation.Description">
                    <ValidationError></ValidationError>
                 </TextEdit>
        </Field>
    </Validation>

    <Validation Validator="ValidateAddress">
         <Field>
             <FieldLabel>Address</FieldLabel>
            <MemoEdit Class="col-sm-12 col-md-10 col-lg-8" Rows="4" MaxLength="100">
                <ValidationError></ValidationError>
            </MemoEdit>
         </Field>
    </Validation>
</Validations>

@code {
    protected override void OnParametersSet()
    {
        Logger.LogDebug("OnParametersSet, validations.ClearAll()");
        validations?.ClearAll();
    }

   //repeated for others
    void ValidateName(ValidatorEventArgs e){
        e.Status = ValidationStatus.Success;
    }

    void Save(){
        validations.ValidateAll();
        //save here
        //don't call validations.ClearAll();
    }


}
```
How to repeat issue: 

(1) `Save()` and don't `validations.ClearAll()` 
(2) Navigate to the same page (with different parameters - so `OnParametersSet()` is called (verified / also that validations != null) and try to `validations?.ClearAll();

Result : the second (2) (not sure why the second) field continues to show the validation 

![image](https://user-images.githubusercontent.com/26474006/63823421-05b01980-c97e-11e9-80fc-1352f50a6b81.png)

**Comment by brettwinters** [comment] 2019-08-28 03:34
#186

**Comment by stsrki** [comment] 2019-09-03 11:35
I cannot reproduce the error. Can you please provide me with the full _non-working_ code example?

Also there are some guidelines you need to follow as I see it from your current example. Validation messages should be inside of `Feedback` as stated in the [documentation](https://blazorise.com/docs/components/validation/).

```
<Validation Validator="@ValidationRule.IsNotEmpty">
    <TextEdit Placeholder="First and last name">
        <Feedback>
            <ValidationError>Enter full name!</ValidationError>
        </Feedback>
    </TextEdit>
</Validation>
```

PS.
Not directly related to your problem but you can use `ColumnSize` on `Field` instead of `Class` on `MemoEdit`. I know it's tempting to use class names directly but I generally not recommend it. Just a friendly advice.

**Comment by brettwinters** [comment] 2019-09-04 02:27
Attached an example: 
[ProductEdit.txt](https://github.com/stsrki/Blazorise/files/3572428/ProductEdit.txt)
(changed ext to "txt" because github won't allow .razor files)

Steps to reproduce

(1) Navigate to "/product/one"
(2) fill in fields, leaving one or more empty
(3) Press "validate" button
(4) Note validation error messages

![image](https://user-images.githubusercontent.com/26474006/64220179-a52b5a00-cef2-11e9-96cd-c933a6db779c.png)

(5) Navigate to another record by pressing say "Load Two"

(6) Note Console output showing that `OnParamatersSet()` is called with new parameter and that `validations.ClearAll()`  is called

![image](https://user-images.githubusercontent.com/26474006/64220306-1f5bde80-cef3-11e9-940b-fc4a1b884628.png)

(7) But note that classes still present on previously un-validated fields 

![image](https://user-images.githubusercontent.com/26474006/64220287-0bb07800-cef3-11e9-84a9-31c20a9f2244.png)

although I note that the <ValidationsError> which generates `<div class="invalid-feedback">
Enter full name!</div>` is removed, but the `is-invalid` class is still there on the `input`)

![image](https://user-images.githubusercontent.com/26474006/64220365-53cf9a80-cef3-11e9-9007-6a3a6584f871.png)

Noted your comment about `Feedback` - sorry must have missed that. What does the feedback do (seems to work the same w and w/o it)

**Comment by stsrki** [comment] 2019-09-04 09:44
I will later try to reproduce error based on your example. 

Regarding the `Feedback` element. It's used as a placeholder for error message(s) when building the html structure. You're using bootstrap so it's just a matter of coincidence that it's working for you. Other css like Bulma have different html structure for input fields so that's why the Feedback is important. To have a placeholder for error messages.

**Comment by stsrki** [comment] 2019-09-09 19:32
Fixed! It will be in released in 0.8.5

**Closed by stsrki** 2019-09-09 19:32 UTC
Labels: investigate, possible-bug
