### ISSUE TITLE
DataGrid no longer scrolls after Popup (Blazorise Modal) closes

### ISSUE THREAD

**Issue by githubfanster** [stsrki/Blazorise#296] opened 2019-10-04 10:21 UTC
DataGrid no longer scrolls after Popup (Blazorise Modal) closes

We're using Blazorise version 0.8.6.1 and Blazor version 3.0 on a Windows 10 desktop machine.
I'm able to replicate the problem we're experiencing when i visit https://bootstrapdemo.blazorise.com/tests/datagrid.
it may involve some sort of interaction between Blazorise Modal and DataGrid only, because i dont experience the problem when i play with the modals in https://bootstrapdemo.blazorise.com/tests/modals.

to reproduce the problem:

(1) go to https://bootstrapdemo.blazorise.com/tests/datagrid
(2) both my laptop and desktop screens have short screens, so i notice that the document with the DataGrid is displayed with a vertical scroll bar and i can scroll the DataGrid
(3) change EditMode from the default 'Form' to 'Popup'. once i blur out of the 'Popup' dropdown and click on a DataGrid area, the DataGrid is scrollable again (so, so far so good)
(4) click on an Edit button
(5) cancel the modal by clicking on the Cancel button that is to the right of the blue Save button
(6) the vertical scroll bar disappears and even after i click on a DataGrid area, i cant scroll thru the datagrid anymore
(7) this remains true even after i go to another page, say, https://bootstrapdemo.blazorise.com/tests/modals, and then go back to the DataGrid demo page. no vertical scrollbar, and the DataGrid demo page looks the same as the last visit so it doesnt seem to get re-rendered to its original good initial state.

Could you please take a look?  Any temporary workaround perhaps? Thanks!

**Comment by stsrki** [comment] 2019-10-04 10:25
I can confirm the issue on my side also. Hm, very strange behavior. I don't remember doing anything with scrollbars. Maybe some CSS rule is messing with scroll. I will check it. tnx for report

**Comment by githubfanster** [comment] 2019-10-07 08:37
here's what we've been able to find out so far.

it looks like if the following code in blazorise's Modal.razor.cs is gettinbg called correctly, everything is fine:

```
private void HandleOpenState( bool isOpen )
        {
            if ( modalBackdrop != null )
                modalBackdrop.IsOpen = isOpen;

            // TODO: find a way to remove javascript
            if ( isOpen )
            {
                ExecuteAfterRender( async () =>
                {
                    await JSRunner.AddClassToBody( "modal-open" );
                } );
            }
            else
            {
                ExecuteAfterRender( async () =>
                {
                    await JSRunner.RemoveClassFromBody( "modal-open" );
                } );
            }

            DirtyClasses();
            DirtyStyles();
        }

```

the attached zip file shows that when "modal-open" css class is added to the html body element,
the scrollbar disappears possibly because the bootstrap css rule for modal-open is:

.modal-open {
   overflow: hidden;
}
 

so, as a temporary workaround, we modified DataGridModal.razor to something like this:

```
@typeparam TItem
...
@inject IJSRunner JsRunner
@namespace Blazorise.DataGrid

<Modal @ref="MyModal" IsOpen="@PopupVisible" Closed="@DoCancel">
    <ModalBackdrop />
    <ModalContent>
        <ModalHeader>
            <ModalTitle>
                Row Edit
            </ModalTitle>
            <CloseButton Clicked="@DoCancel" />
        </ModalHeader>
        <ModalBody>
            ...
        </ModalBody>
        <ModalFooter>
            @if (ParentDataGrid?.CommandColumn?.SaveCommandTemplate != null)
            {
                @ParentDataGrid.CommandColumn.SaveCommandTemplate(new CommandContext<TItem>
                {
                    Clicked = Save,
                    Item = EditItem,
                })
            }
            else
            {
                <Button Color="Color.Link" Clicked="@DoSave">Save</Button>
            }
            @if (ParentDataGrid?.CommandColumn?.CancelCommandTemplate != null)
            {
                @ParentDataGrid.CommandColumn.CancelCommandTemplate(new CommandContext<TItem>
                {
                    Clicked = Cancel,
                    Item = EditItem,
                })
            }
            else
            {
                <Button Color="Color.Link" Clicked="@DoCancel">Cancel</Button>
            }
        </ModalFooter>
    </ModalContent>
</Modal>

@code{

    Modal MyModal { get; set; }


    async Task DoCancel()
    {
        await JsRunner.RemoveClassFromBody("modal-open");
        Cancel.InvokeAsync(null);
    }

    async Task DoSave()
    {
        await JsRunner.RemoveClassFromBody("modal-open");
        Save.InvokeAsync(EditItem);
    }
}

```

**Comment by githubfanster** [comment] 2019-10-07 08:39
the zip file. sorry
[blazorise-modals.zip](https://github.com/stsrki/Blazorise/files/3696246/blazorise-modals.zip)

**Comment by stsrki** [comment] 2019-10-07 10:36
Thank for pointing me in the right direction. I don't want to expose `JSRunner.RemoveClassFromBody` outside of Blazorise as it's meant to be internal handler. Anyways I will try to look for another way to handle "modal-open" flag.

**Comment by Herdo** [comment] 2019-10-31 21:42
@stsrki I can confirm that this issue doesn't only apply to DataGrid, but to every scroll viewer when using a modal.

From debugging the JavaScript code, it seems that the class `modal-open` is directly added to the body again, after it was removed. Here's log output:
```
removeClassFromBody - 'modal-open'
  removeClass - 'modal-open'
addClassToBody - 'modal-open'
  addClass - 'modal-open'
```

After further playing around, it seems that the issue is caused by using the `IsOpen` property of the `Modal` class. When `IsOpen` is set to `true`, and the dialog is hidden by `Hide()`, the css class `modal-open` remains on the `body` element.

If, instead, not using the `IsOpen` property at all, and only working with the `Show()` and `Hide()` method, the css class `modal-open` is correctly removed after closing the dialog.

**Side note:** using nested modal dialogs (e.g. a cookie consent dialog, opening another dialog with an excempt of the privacy policy, totally messes up the modal behavior. I'm not sure if there is any correct way to do "nested modals", or if this is, by design, just not wanted.

**Closed** 2019-12-27 14:16 UTC
Labels: bug, investigate

**Comment by ryanph-javs** [comment] 2021-01-25 22:01
@stsrki Can you take another look at this? I am having this issue as well. The problem seems to be rooted in the `ModalBackdrop`. If I remove that I can scroll with no issues but if it's there I can't scroll at all. I'm using bootstrap as well.

**Comment by stsrki** [comment] 2021-01-26 08:21
@ryanph-javs It's already on the list for this milestone #877
