### ISSUE TITLE
how to creat Double Clustered Column chart ?

### ISSUE THREAD

**Issue by linhtinh123cz** [stsrki/Blazorise#1969] opened 2021-03-06 10:55 UTC
I am trying to do  Double Clustered Column 
![sxB0p](https://user-images.githubusercontent.com/50605180/110204340-11e73200-7ea5-11eb-90dd-3a320f01f3f6.png)

but don't know how .

**Comment by stsrki** [comment] 2021-03-06 13:57
You can add as many dataset. Here I just added one more to the list: `await chart.AddLabelsDatasetsAndUpdate( Labels, getDataSet(), getDataSet() );`

![image](https://user-images.githubusercontent.com/900302/110209326-2b2fb480-7e8c-11eb-8d1e-c197fd9e21cb.png)

**Comment by tupx333** [comment] 2021-03-11 06:49
I got a problem with backgroud firt colum when i click on it don't have color  
![chartb](https://user-images.githubusercontent.com/80302740/110747140-7709a180-8270-11eb-8dde-c27373dbd711.png)
and when i redraw it back to normal

**Comment by stsrki** [comment] 2021-03-11 08:46
Closing because the original issue was resolved.

@tupx333 You probably didn't define the same number it colors and the same number of data. Eg.

```diff
BarChartDataset<double> GetBarChartDataset()
{
return new BarChartDataset<double>
{
    Label = "# of randoms",
+    Data = RandomizeData(),
+    BackgroundColor = backgroundColors,
    BorderColor = borderColors,
    BorderWidth = 1
};
}
```

Notice Data and BackgroundColor. They must match 1=1. If Data has 5 elements then BackgroundColor also must have 5 elements.

**Closed by stsrki** 2021-03-11 08:46 UTC

**Comment by tupx333** [comment] 2021-03-11 08:56
i have 8 elements , if i click redraw the color is back.

**Comment by tupx333** [comment] 2021-03-11 08:56
> Closing because the original issue was resolved.
> 
> @tupx333 You probably didn't define the same number it colors and the same number of data. Eg.
> 
> ```diff
> BarChartDataset<double> GetBarChartDataset()
> {
> return new BarChartDataset<double>
> {
>     Label = "# of randoms",
> +    Data = RandomizeData(),
> +    BackgroundColor = backgroundColors,
>     BorderColor = borderColors,
>     BorderWidth = 1
> };
> }
> ```
> 
> Notice Data and BackgroundColor. They must match 1=1. If Data has 5 elements then BackgroundColor also must have 5 elements.
i have 8 elements , if i click redraw the color is back.

**Comment by stsrki** [comment] 2021-03-11 08:58
Please open a new ticket, and post a fully working code to quickly reproduce it.
