### ISSUE TITLE
Autocomplete Component SelectedValueChanged bug

### ISSUE THREAD

**Issue by Darhness** [stsrki/Blazorise#1277] opened 2020-08-25 14:18 UTC
**Describe the bug**
After adding the "SearchChanged" and "SelectedValueChanged" tags to the Autocomplete, IF you select a new value, the "TextField" won't change(the placeholder will be shown).

**Expected behavior**
Show the content of "TextField" parameter.

**Comment by stsrki** [comment] 2021-04-12 19:59
Should be fixed in the latest 0.9.3.x version. Please reopen if the problem is still present.

**Closed by stsrki** 2021-04-12 19:59 UTC
