### ISSUE TITLE
Unable to scroll in Chrome when an extra large modal is visible

### ISSUE THREAD

**Issue by aherbage** [stsrki/Blazorise#1068] opened 2020-07-03 13:46 UTC
When I display an extra large modal in Chrome, if the browser window is too small to contain the entire modal, a vertical scrollbar appears. Using the mouse wheel to scroll has no effect. Clicking anywhere on the scrollbar closes the modal.

Scrolling works as expected in Microsoft Edge.

1. Create a page with an extra large modal
2. Open the page in Chrome
3. Resize the browser window so it will be smaller than the modal
4. Open the modal
5. Click on the scrollbar, to try to scroll down

**Expected behavior**
One should be able to use the scrollbar to view the entire modal

**Comment by stsrki** [comment] 2020-07-03 13:59
This is duplicate of #877 

The plan is to work on it with on 0.,9.2 milestone.

**Closed by stsrki** 2020-07-03 13:59 UTC
