### ISSUE TITLE
Add ElementRef to all components

### ISSUE THREAD

**Issue by StefH** [stsrki/Blazorise#981] opened 2020-06-13 14:21 UTC
I've this code:
*html*
``` html
<CardHeader @ref="IntakeCountHeader"></CardHeader>
```

*c#*
``` cs
CardHeader IntakeCountHeader;
```
The element is rendered as (no `id` attribute is defined?)
``` html
<div class="card-header" style=""></div>
```

And in C# code, the value from `IntakeCountHeader.ElementRef` is invalid.
And using the `elementId` does not work, this id is just generated and not really applied to the dom?

When using a normal div like this:
``` html
<div class="card-header" @ref="IntakeCountHeaderRef"></div>
```
and c# code like:
``` cs
ElementReference IntakeCountHeaderRef;
```

I can get the reference + the id, and the html is rendered like:
``` html
<div class="card-header" _bl_bd850534-a4b6-4e7c-88df-301aa29b388e="">
```

**Comment by stsrki** [comment] 2020-06-13 18:11
This is by design. When you do `<CardHeader @ref="IntakeCountHeader"></CardHeader>`, you get the reference to the CardHeader. It's not the same as reference on the underline div element. In fact their types are also completely different. `ElementReference` vs `CardHeader`.

The next thing and why there is no `id` or `@ref` applied on the `div` element, in this case. The reason is that I only apply those on the elements that I need to use by the JS over JSInterop. They are not meant to be used outside of Blazorise. In the case of CardHeader or similar component it can be doable but then there is a lot of complicated components with multiple nested element like div, span, input, etc. Obviously one `ElementReference` could not be used for all of them.

One example of Select component implemented in AntDesign

```cshtml
<div @ref="@ElementRef" id="@ElementId" class="@ContainerClassNames" style="@StyleNames" disabled="@Disabled" readonly="@ReadOnly" @attributes="@Attributes">
    <div id="@SelectorElementId" class="ant-select-selector" @onclick="@OnSelectorClickHandler">
        @if ( Multiple )
        {
            foreach ( var selectedValue in SelectedValues ?? Enumerable.Empty<TValue>() )
            {
                var tempValue = selectedValue;

                <span class="ant-select-selection-item">
                    <span class="ant-select-selection-item-content">@selectedValue</span>
                    <span @onclick="@(_ => OnMultipleValueClickHandler( tempValue ))" class="ant-select-selection-item-remove" unselectable="on" aria-hidden="true" style="user-select: none;">
                        <span role="img" aria-label="close" class="anticon anticon-close">
                            <svg viewBox="64 64 896 896" focusable="false" class="" data-icon="close" width="1em" height="1em" fill="currentColor" aria-hidden="true"><path d="M563.8 512l262.5-312.9c4.4-5.2.7-13.1-6.1-13.1h-79.8c-4.7 0-9.2 2.1-12.3 5.7L511.6 449.8 295.1 191.7c-3-3.6-7.5-5.7-12.3-5.7H203c-6.8 0-10.5 7.9-6.1 13.1L459.4 512 196.9 824.9A7.95 7.95 0 00203 838h79.8c4.7 0 9.2-2.1 12.3-5.7l216.5-258.1 216.5 258.1c3 3.6 7.5 5.7 12.3 5.7h79.8c6.8 0 10.5-7.9 6.1-13.1L563.8 512z"></path></svg>
                        </span>
                    </span>
                </span>
            }
        }
        <div class="ant-select-selection-search">
            <input id="@InputElementId" class="ant-select-selection-search-input" role="combobox" readonly multiple="@Multiple" value="@CurrentValueAsString" aria-haspopup="listbox" aria-owns="@SelectListId" aria-controls="@SelectListId" aria-expanded="@Expanded.ToString().ToLowerInvariant()" />
        </div>
    </div>
</div>
<div class="@DropdownClassNames" style="@DropdownStyleNames">
    <div>
        <div class="" style="@DropdownInnerStyleNames">
            <div>
                <div class="" style="display: flex; flex-direction: column;">
                    @ChildContent
                </div>
            </div>
        </div>
    </div>
</div>
```

Notice I I used `@ElementRef` on div and not the input, As you can see it's pretty complicated area. You must also remember that Blazorise is just an abstraction over different components. I hope you now understand it all much better.

**Comment by StefH** [comment] 2020-06-13 18:49
My assumption was that because of `<CardHeader"></CardHeader>` is translated to `<div class="card-header"></div>` which means that in that case I expected that `IntakeCountHeader.ElementRef` would be defined as a reference to the **div**.

**Comment by xxCruciblexx** [comment] 2020-06-13 22:35
I understand the frustration. It could be added to some without worry, I’ve had this issue myself.  Scary jumping in but one idea is to use the project directly instead of NuGet. You will learn how it all works, and also find and debug what you need in your project and can then modify it to work with your situation. It’s no fun but everything can’t be incorporated or it would be useless to everyone.

**Comment by stsrki** [comment] 2020-06-14 11:33
> My assumption was that because of `<CardHeader"></CardHeader>` is translated to `<div class="card-header"></div>` which means that in that case I expected that `IntakeCountHeader.ElementRef` would be defined as a reference to the **div**.

Yeah that would work for some components but since I don't apply the ElementRef to all of them, in this case it will not work.

I've being thinking more about this since yesterday, and I think it should not be a problem to apply ElementRef and ElementId to every component in Blazorise. Even in the cases when there is complex markup involved behind the scenes you can still be able to get the right element with a little JavaScript DOM selectors. As soon as you wish to use ElementRef and ElementId it means you're on advance level so you're on your own. I can give you means you find a way 😎

**Comment by stsrki** [comment] 2020-10-02 14:29
Moving to the next milestone for the same reasons mentioned in #791

**Comment by stsrki** [comment] 2020-12-24 10:08
While I was working on #791 I decided to not go with this feature. It would make little sense to define ElementReference from outside the component. It's only used internally in a specific places. And `@ref` on a component is different than `@ref` on an element.

If you need to get the underline element you can do it with `ElementId` parameter done in #791. After that it's as simple as `document.getElementById(elementId);`

**Closed by stsrki** 2020-12-24 10:08 UTC
Labels: Type: Architecture
